const README = `
<h3>1. What the three tabs are</h3>
<p><b>PriceCharting Catalog</b> is the card list with PriceCharting's prices and the trend columns built from this site's own daily snapshots. <b>eBay Catalog</b> is the same card list with numbers computed <i>only</i> from eBay: every raw (ungraded) single listed in the last 30 days, matched to a card by its title, followed until it sells or ends. <b>eBay Raw Data</b> is the listings themselves — every matched raw single first seen in the last 24 hours, with the buy verdict. The eBay side is fed by a collector running around the clock on a small rented machine: it reads eBay's newest listings every minute, re-checks older ones for sales, and publishes every couple of minutes; the two eBay tabs pick the new data up on their own, and Raw Data tints rows that arrived since your last look.</p>
<p><b>All eBay prices are buyer totals: item + shipping.</b> That is what the buyer paid and what you compare against, and because you list with free shipping, the Sell price is literally the number you type into the listing.</p>

<h3>2. Reading the eBay Catalog: three bands</h3>
<p><span class="legend"><span class="l-obs">Observed</span></span> columns are independent inputs measured on eBay — counts, the book of competing copies, sold prices. <span class="legend"><span class="l-rate">Rates</span></span> are computed from Observed only (λ, Price, Days supply, In/out). <span class="legend"><span class="l-dec">Decisions</span></span> depend on the two anchors (sections 3 and 4) and your <b>Confidence</b>, <b>Window</b> and <b>Margin</b> settings at the top — change those and only the amber band moves. Every header's <b>?</b> shows the formula, an example, what the column is built from and what it feeds.</p>

<p>A fourth band, <span class="legend"><span class="l-tr">Trends</span></span>, applies the PriceCharting tab's trend formulas to eBay's own realized prices: the price line is the median of raw sale totals over a trailing 7-day window (blank with fewer than 3 sales in the window), and the Trend button charts it with sales per day and the cheapest ask. These fill in on the same schedule as the PriceCharting versions — 7, 30 and 60 days after the collector started — and are noisier on thin cards, where the median moves because different copies sold rather than because the market did.</p>

<h3>3. The sell price — two anchors, worked through</h3>
<p>The Sell price answers one question: <i>what do I list at so this card goes inside my window without giving money away?</i> Two numbers answer it, and the lower one wins.</p>
<p><b>Anchor A — what buyers actually pay.</b> Take the card's comparable sales over the last 30 days (60 if there are fewer than 5), with Lightly Played sales lifted to NM-equivalent. Example, twelve sales: $88, 90, 92, 94, 95, 96, 98, 99, 102, 105, plus a <b>$150</b> Best Offer sale recorded at its asking price and a <b>$42</b> copy that was really a different printing. Two trims throw the junk out: anything outside the Tukey fences (1.5 × the interquartile range beyond the middle half) and anything outside a quarter to four times the median. $150 and $42 both go. The ten that remain are weighted by recency (a sale 10 days old counts half as much as one today, 20 days old a quarter) and combined with a robust centre: a weighted median under 8 sales, the Hodges–Lehmann estimator from 8 up — the median of all pairwise averages, the same device as the Theil–Sen slope on the trend columns, about 15% less noisy than a plain median and still immune to a few bad points. Here <b>A = $94</b>. The Anchor column shows "thin" and the gate stays shut until a card has 5 sales behind A.</p>
<p><b>Floor L — the cheapest copy you must actually beat.</b> Now the open copies. Say the book is $40, $70, $85, $96, $99, $104. Not all of these are competition:</p>
<ul>
<li>the <b>$40</b> copy is under 75% of A — it is a deal to buy or a copy with something wrong, not a price to match;</li>
<li>the <b>$85</b> copy is from a 3-feedback seller (watch tier) — shown, never a price-setter; the same for any seller under 50 ratings or under the feedback bar;</li>
<li>the <b>$70</b> copy has sat 9 days on a card that sells every other day — a credible copy on this card is gone within about 1.6 ÷ λ = 3 days, so buyers have looked at it and passed;</li>
<li>the <b>$96</b> copy takes Best Offers, so it ranks at 90%: <b>$86.40</b>.</li>
</ul>
<p>The credible floor is <b>L = $86.40</b>. Then</p>
<div class="formula">Sell = min(L − $0.50, 0.95 × A) = min(85.90, 89.30) = 85.90 → rounded down to <b>$84.99</b></div>
<p>With no credible copy at all, Sell = 0.93 × A. When a card has 8 or more sales that sold within 48 hours of listing, their median caps the price too — the price that provably sells fast. The old rule, "cheapest copy minus a dollar", would have listed this card at $39 because of the $40 copy; that is why the Decisions band was wrong whenever the book had junk in it, which on a 4-day-old collector was most of the time.</p>

<h3>4. Will it sell inside the window? — the liquidity rule</h3>
<p>Buyers for a card arrive at a rate λ (sales per day, stated conservatively as the 25th percentile of the Gamma posterior, so a card with 12 sales in 18 days reads 0.56 rather than 0.67). If they arrive at a steady average rate, the chance that at least one shows up inside T days is 1 − e<sup>−λT</sup>. Demanding that chance be at least your Confidence turns into a rate the card has to clear:</p>
<div class="formula">λ needed = −ln(1 − Confidence) ÷ T days
48 h at 70% → 0.60/day     48 h at 80% → 0.80/day     48 h at 90% → 1.15/day     72 h at 70% → 0.40/day</div>
<p>A card that clears it (and, once measured, has a 7-day sell-through of at least 50%) is <b>liquid</b>; otherwise its Max buy is greyed "illiquid" and nothing on it can pass. This is the single biggest lever on how many cards are eligible: 48 hours at 80% needs roughly 24 sales a month; 72 hours at 70% needs 12. The Window and Confidence boxes let you see that trade-off instead of inheriting it — one extra day of holding against an 8–14 day cash cycle (section 9) is cheap. The rest of the old Poisson machinery — pricing off the second-cheapest copy because two buyers are expected — is gone: it assumed buyers take strictly the cheapest copy, which eBay's photos, feedback and promoted placement make untrue.</p>

<h3>5. The buy gate</h3>
<p>What you keep from a sale at price S, listed with free shipping:</p>
<div class="formula">net = S × (1 − 0.1325 × 1.065) − $0.40 − $4.50 − $0.30 = 0.8589 × S − $5.20
   eBay's 13.25% is charged on the buyer's total including their sales tax; $0.40 per order; $4.50 tracked label; $0.30 sleeve, top loader and mailer
Max buy = net ÷ (1 + Margin)</div>
<p>On the example card: net = 0.8589 × 84.99 − 5.20 = <b>$67.80</b>; at a 10% margin Max buy = <b>$61.63</b> all-in. All-in is what leaves your account: item + shipping + the <b>Buy tax</b> box (Massachusetts sales tax, 6.25%). A $58 copy with free shipping is $61.62 all-in and <b>passes</b>; $59 does not. In words: about 24% of every sale is gone before any profit, so a hit has to be roughly 31% under the Sell price at a 10% margin, 34% at 15%. That is why hits are rare and why the margin defaults to 10% now: with deal flow rather than cash as the limit, capital sitting idle at 15% earns nothing.</p>
<p><b>The resale certificate.</b> A Massachusetts vendor registration plus a resale certificate (Form ST-4) filed with eBay's tax-exemption program stops eBay charging sales tax on your purchases for resale. The day that approval lands, set the Buy tax box to 0: the all-in cost of every listing drops 6.25%, breakeven moves from about 24% to under 19% of the sale price, and the $61.63 Max buy above lets you pay $61.63 delivered instead of $58. Do not set it to 0 before the approval is real — the page would call listings hits that still cost you 6.25% more, and a 10% margin would quietly become 3.75%. The box is remembered in this browser and changes nothing in the collector, whose hourly log keeps counting at 6.25% until it is told otherwise.</p>
<p>Three details. Each listing is judged against the book <i>without itself</i>: you buy it, it leaves the market, and your relist competes with what remains — before this fix a cheap listing became its own card's cheapest copy and had to be 30% cheaper than itself. A Lightly Played listing is judged at the LP-discounted sell price. And a listing under <b>45% of A</b> gets a "review" badge instead of a verdict: at that price it is more often misidentified, damaged or fake than a bargain, so you spend thirty seconds on the photos and the seller before anything else.</p>

<h3>6. What to do with the numbers</h3>
<ul>
<li><b>Buy</b> when the verdict says PASS — then read the title, the photos and the seller, and open the card's <b>Book</b> to see the copies you would compete with (greyed rows are the ones the floor ignored, and why).</li>
<li><b>List</b> at Sell, free shipping, Best Offer on with auto-accept about 3% under it. Unsold at 36–48 hours, cut to 0.90 × A or accept offers there. After another window it was mispriced or the card slowed — take the small loss and note why.</li>
<li>Treat "review" rows as a short daily to-do, not as hits. The same goes for the <b>Too cheap only</b> list (section 14): mostly wrong matches, occasionally a real steal.</li>
</ul>

<h3>7. The Confidence, Window and Margin boxes</h3>
<p><b>Only show hits</b> filters the Raw Data tab to PASS rows. <b>Confidence</b> and <b>Window</b> together set the sales rate a card needs to count as liquid (section 4); they move nothing else. <b>Margin</b> is the profit required on all-in cost; it moves Max buy and the PASS threshold and nothing else. <b>Net $</b> on the Catalog is what you clear at the Sell price; <b>Profit $</b> and <b>ROI %</b> on the Raw Data tab apply that to each listing's all-in cost, so sorting Raw Data by ROI shows the best buys first. The boxes are remembered in this browser and change nothing in the collector.</p>

<h3>8. Calibration — of the price, not the rate</h3>
<p>λ is left exactly as the data says. What gets checked is the price claim. When a listing first appears, the collector records the Sell price the model would have set for its card at that moment, and how far above or below it the listing was priced. Two days later the tracker knows whether it sold. Pooling every listing that entered the buyable top of its book gives a table: realized 48-hour sell-through by offset from Sell. If listings at the model's price sell far less than 70% of the time and it takes being 7% cheaper to get there, Sell shifts by 7% — the <b>Calibration</b> box shows the measured offset and how many outcomes it rests on, and applies it once there are at least 150 outcomes with 25 in each bucket around the crossing. The Scam screen button also shows <b>how fast cheap listings go</b>: closed listings grouped by their price relative to A when first seen, with how many sold within 1, 6, 24 and 48 hours. That table answers the question the whole system turns on — whether listings at 60–70% of the anchor are gone within an hour (the scanner must be faster) or sit for days (they were cheap for a reason).</p>

<h3>9. Where hits come from — and the real cash cycle</h3>
<p>Two facts shape expectations. First, the fee wedge: a hit is a 31%-off listing on a card that sells daily, and other scanners watch the same new-listing feed, so genuine ones are rare and go in minutes. Second, "sell within 48 hours" is not a 48-hour cash cycle: inbound shipping (3–5 days), the sale, outbound delivery (2–5 days) and eBay's payout hold (1–3 days) make it <b>8–14 days</b>, so a dollar turns two or three times a month, not fifteen. Realistic early output, if the guesses hold: a few buys a day across all channels at $7–12 each on $100 cards.</p>
<p>The steadier sources of 30%-off buys are the ones a new-listing scanner never sees: Best Offers on listings that have sat ten days or more, auctions ending at odd hours, and price drops on old listings (a relist or a cut never appears as "new"). The planned next step is a daily offer list — the site computes the price to offer on aged listings of liquid cards and you click through on eBay, since eBay's API will not send offers — built once the deal-speed table says what new listings deliver on their own. Two housekeeping items are worth real money: verify your actual label cost (two dollars moves breakeven two points), and look into a Massachusetts resale certificate filed with eBay, which removes the 6.25% buying tax and moves breakeven from 24% to under 19% of the sale price — confirm the obligations with the state before relying on it.</p>

<h3>10. When demand exceeds supply — the fix to apply later</h3>
<p><b>The signature:</b> Sell-thru ≥ 80%, Days supply under 3, Hrs to sale short, few Active copies. Copies vanish within hours of appearing.</p>
<p><b>The problem:</b> on such a card the count of sales is capped by the count of copies listed. Five copies in a month means at most five sales, so λ from counts comes out low — the model says 60% when reality is closer to 95%, prices too cautiously, and you pass on deals or list too cheap on exactly the cards where you could hold out. The error is in the safe direction, which is why it is tolerated for now.</p>
<p><b>The fix:</b> use time-to-sale, which supply cannot cap. If copies typically sell 20 hours after listing, buyers are arriving at least every 20 hours whether or not a copy exists. For an exponential wait the median is ln 2 ÷ λ, so</p>
<div class="formula">λ_wait = ln 2 ÷ (median hours to sale ÷ 24)     e.g. 20 h → 0.693 ÷ 0.833 = 0.83 sales/day</div>
<p>even if only five copies were ever listed. Because not every sold copy sat at rank 1, this still understates demand a little, which keeps it conservative.</p>
<p><b>What to do:</b> after two or three weeks, look at the Hot cards (candidate or confirmed) and compare their λ column with ln 2 ÷ (Hrs to sale ÷ 24). If the waiting-time number is consistently and clearly higher on the confirmed ones, switch the collector to use λ_wait whenever the signature above is present (Sell-thru ≥ 80% and Days supply &lt; 3, with at least 5 sales) — it is a few lines in compute_stats() in ebay_sweep.py. Do not switch before the data shows the gap; changing a model before you can check it is how you end up trusting the wrong number.</p>

<h3>11. Hot cards</h3>
<p>Five checks from history: k ≥ 5, Sell-thru ≥ 80%, median Hrs to sale ≤ 48, sales realized at ≥ 95% of the median ask, and the last five sales not more than 3% below the five before. Passing all five makes a <b>candidate</b>. The next three copies listed after the flag are then watched: all three selling within 48 hours makes it <b>confirmed</b> (a test on data the checks never saw); one sitting longer resets the count. Confirmed cards are the ones where you can pay close to full Max buy, because the exit is nearly certain — and where deals will be scarcest.</p>

<h3>12. Condition and the LP correction</h3>
<p>Demand and supply are condition-blind: a buyer who takes a Lightly Played copy is a real buyer, and an LP copy in the book is a real competitor. Price is not. So the Catalog counts NM, LP and unstated listings alike, but lifts every LP price to NM-equivalent (an LP sale at $83 is treated as $94.32 at a 12% correction) before computing the anchor, the floor and the Sell price — the Catalog's prices are NM prices. On Raw Data the correction runs the other way: a listing that says LP has its sell price cut by it, so its Max buy, Profit, ROI and verdict are for a played copy (hover Max buy to see the NM figure). Not-stated listings are treated as NM. MP and HP are a different market and stay out entirely.</p>
<p>The correction is read-only and shown next to Margin for three price tiers (under $100, $100–150, $150+), because condition costs more on an expensive card. It starts at 12% and is replaced by the measured LP-to-NM ratio — pooled across every card, since no single card has enough LP sales — once a tier has 30 LP sales behind it; a tier without enough sales uses the ratio measured across all tiers, and until that exists, the default. Hover a tier to see where it stands.</p>

<h3>13. The scam screen</h3>
<p>Scam listings hurt twice: they show up as the best "deals", and while they are live they sit in the card's book as the cheapest copy and would drag the floor and Max buy down for everyone. eBay removes them eventually, but only after the damage. So every listing gets a score from cheap signals — how far under the card's price it is, the seller's feedback count and whether their percentage clears the bar for that count, one photo, a stack of copies of a card that does not come in stacks, a photo already used by another seller, no returns on a cheap listing, a long delivery window, with credit for Top Rated Plus and long-established sellers. No single signal decides: an honest new seller at a fair price scores 3 and stays. Score 5 or more is <b>suspect</b>: kept out of every statistic and hidden on Raw Data behind the Show suspects box. 3–4 is <b>watch</b>: in the statistics, badged, but never allowed to set the floor. Raw Data also leaves out any listing with fewer than 2 photos, because condition cannot be judged without the back — the Catalog still counts those listings, since buyers buy from them.</p>
<p>The score is calibrated from outcomes, like the price: every closed listing keeps the score it had, and the Scam screen button tabulates how each tier and each signal turned out — sold, ended, or "gone" (pulled before its end date, which is what eBay does to scams). A signal that fires mostly on listings that later vanish is earning its points; one that fires on listings that sold normally is catching honest sellers and gets cut. Thresholds are adjusted by hand from that table, not fitted automatically.</p>

<h3>14. Is it the right card? — the identity checks</h3>
<p>Every number above assumes a listing really is the card it was filed under. A wrong match hurts twice: it can look like a bargain (a reverse holo, a jumbo, a Japanese copy or a reprint filed under the expensive card), and it drags that card's prices. Four things guard against it.</p>
<ul>
<li><b>The title match</b> goes by card number first, then the set — by its words in the title or its printed total ("/165", from the open Pokémon TCG set list) — then the card's name, which has to agree, then the printing. When two sets hold the same number and name, the printed total decides: a Charizard titled "4/130 Base" is Base Set 2 (130 cards), not Base Set (102). A title that names a printing the catalog does not list for that card (reverse, 1st edition, jumbo, Master Ball…) is left unmatched rather than filed under the plain card. The catalog product a seller picked on eBay is used only when the title agrees with it.</li>
<li><b>Price against PriceCharting</b> — the one place a PriceCharting price is used on the eBay tabs. A listing under <b>40%</b> or over <b>300%</b> of the card's PriceCharting ungraded price is marked <b>mismatch</b>: it can never be a hit, and it is left out of the book, the sold prices, λ and the trends. Example: a $40 listing filed under a $120 card is at 33% → mismatch ↓; $420 is at 350% → mismatch ↑; $70 (58%) is judged normally. The rule is skipped when PriceCharting has fewer than 20 sales a year behind its price, when the set is under 30 days old (new-set prices fall faster than PriceCharting follows), and on the cheap side for MP/HP copies. Tick <b>Too cheap only</b> on Raw Data to go through the cheap ones by hand.</li>
<li><b>Item specifics.</b> A listing that clears the price gate is looked up once, and what the seller entered — card number, card name, set, language, card size, finish — is compared with the matched card. <b>PASS ✓</b>: they agree. <b>PASS ID?</b>: not read yet, or the seller left them blank, so the match rests on the title. <b>ID conflict</b>: they describe another card; hover the badge for what disagreed. A wrong printed total alone ("155/168" on a /128 set) is noted, not treated as a conflict, when the number, name and set agree.</li>
<li><b>Your eyes.</b> None of this reads the photos. Before any buy: front and back, the number in the corner, the language, the stamp.</li>
</ul>
<p>The four numbers of the price rule are constants at the top of the collector (PC_LOW, PC_HIGH, PC_MIN_SALES, PC_NEW_SET_D). How often the matcher is right has not been measured yet: sort Raw Data by <b>vs PC %</b> ascending, open the first 150 listings, and count how many are really the card in the first columns — that count is the first real accuracy number, and the misses show which rule to tighten.</p>

<h3>15. What the model does not see</h3>
<p>Promoted listings outrank you at equal price. Auctions ending in the window soak up buyers. Best Offer sales are recorded at the ask, so sold prices can run ~10% high. Titles the parser cannot resolve to one card are skipped, not guessed — the Unmatched button on the Raw Data tab lists them. And the Browse API only reports sales for listings that were seen while live, so history starts the day the collector was switched on and grows forward.</p>
`;

/* ---------------- Column help ---------------- */
const pct = v => (v * 100).toFixed(2).replace(/\.?0+$/, '') + '%';
const HELP = {
  card: {t: 'Card', f: 'PriceCharting product name = card name + [variant] + #number', m: 'Each printing is its own row with its own prices: a plain card, its [Reverse Holo], [Holo], [1st Edition] or [Shadowless] version are different products. The name links to the PriceCharting page.', e: '"Spinarak #6" and "Spinarak [Ditto] #6" are the same card number in the same set, at $0.83 and $15.24 — a seller who lists only "Spinarak 6/78" may not know which one they have.'},
  set: {t: 'Set', f: 'PriceCharting console-name', m: 'The set the card was printed in, in PriceCharting\'s naming. The table and the set dropdown are ordered by each set\'s release date.', e: '"Pokemon Base Set" (1999) sorts before "Pokemon Jungle" (1999-06) before "Pokemon Evolving Skies" (2021).'},
  num: {t: 'Set / Card', f: 'card number / printed set size, as the card itself shows it (36/123 = card 36 of a 123-card set)', m: 'The number after the slash is the set\'s printed size, taken from the open Pokemon TCG dataset and matched to PriceCharting\'s set names when the site is built each morning; a set that did not match uses the size the collector learns from eBay titles (most say "36/123") once it has seen it five times, and shows the bare number until then. Prefixed numbers (TG05, SV001, GG05) are shown as printed. Set + number + printing identify a card: a reverse holo, 1st Edition or shadowless printing shares the number and is its own row, tagged in the Card column. Secret rares run past the printed size (199/165).', e: 'Charizard ex 199/165: card 199 of Obsidian Flames, whose printed size is 165. Base Set 4/102 is Charizard; Jungle 4/64 is Kangaskhan.'},
  released: {t: 'Released', f: 'PriceCharting release-date', m: 'The card\'s original release date. Cards without one show "—" and their set is ordered by the earliest dated card in it.', e: '1999-01-09 for Base Set; 2022-07-01 for Pokémon Go.'},
  sales: {t: 'Sales/yr', f: 'PriceCharting sales-volume = units sold in the trailing 12 months, ALL grades combined', m: 'A liquidity measure — but it counts raw and graded sales together. For cheap modern cards almost nothing is graded, so it ≈ raw sales. For vintage cards graded sales can be most of it, so it overstates how often a raw copy sells. Use the Trend popup\'s "raw sale every N days" for the raw-only view.', e: 'Ivysaur #2 (1998 KFC): 45/yr in this column, but PriceCharting\'s page shows ungraded ≈ 12/yr, Grade 8 ≈ 12, PSA 10 ≈ 12, Grade 7 = 6, Grade 9 = 3. 12+6+12+3+12 ≈ 45.'},
  ungraded: {t: 'Ungraded $', f: 'PriceCharting loose-price', m: 'The market price of an ungraded copy — a trailing average of recent raw sales (mostly eBay). This is the anchor: every other number is measured against it. It only moves when new raw sales land, so a slow card\'s price can sit unchanged for weeks. It blends all conditions; a near-mint copy sells closer to the Grade 7–8 price.', e: 'If the anchor is $42.00 and a listing is $27.99 + $4 shipping, the listing is 76% of anchor before tax — then fees, shipping out and drift decide whether that is a deal (see Trend popup).'},
  d7: {t: 'Δ7d %', f: '(P_today − P_7_days_ago) / P_7_days_ago × 100', m: '"Did something just happen." On a slow card this is usually one sale landing, so pair it with a Sales/yr floor before trusting it. Sort descending for cards that just jumped (sell candidates), ascending for cards that just dropped.', e: '$42.00 today, $42.50 a week ago → (42.00 − 42.50) / 42.50 = −1.2%.'},
  d30: {t: 'Δ30d %', f: '(P_today − P_30_days_ago) / P_30_days_ago × 100', m: 'The core trend number and the one to sort by. Read it with Δ7d and the slope: 30d down but 7d flat and the slope flattening is a card that may be settling; all of them down is a card still falling. A drop is either mispricing (opportunity) or news (a reprint, a rotation) — the number cannot tell which.', e: '$42.00 today, $48.00 thirty days ago → (42.00 − 48.00) / 48.00 = −12.5%.'},
  pos: {t: 'Range 90d %', f: '(P_today − Low_90d) / (High_90d − Low_90d) × 100', m: 'Where today\'s price sits between its 90-day low (0%) and high (100%). Two cards can both be −12% over 30 days: one falling back from a spike (still at 85% of its range) and one making new lows (5%). Different bets. Ignore it when the range is tiny, and remember a low position during a steady decline is a falling knife — it is only a signal once the 30-day trend has flattened. Needs 60 days of history.', e: 'Low $38.00, high $52.00, today $42.00 → (42 − 38) / (52 − 38) = 4 / 14 = 29%.'},
  vd: {t: 'Volume drift 30d', f: 'Sales/yr_today − Sales/yr_30_days_ago   (and as % of the earlier value)', m: 'Because Sales/yr is a trailing 365-day count, the 30-day difference equals (sales in the last 30 days) minus (sales in the 30-day window that just fell out of the year — roughly the same month a year ago). So a positive number means this month beat the same month last year: a year-over-year demand signal that is automatically seasonally matched. It counts all grades, so on vintage cards it is mostly a graded-market signal, and small counts are noise — +2 on a base of 40 means nothing. Sorting and the range filter use the percent. Rising volume with a rising price is real heat; rising volume with a falling price is a supply flood (a reprint hitting the market), the pattern where a "bargain" keeps getting cheaper.', e: '210 today, 196 thirty days ago → +14 sales, +14 / 196 = +7.1%.'},
  vol: {t: 'Volatility %', f: 'median of |ln(P_t / P_t−1)| over the days the price moved in the last 90 days', m: 'The typical size of a move when the price moves. The median ignores a single wild day, which a standard deviation would not. It sizes the safety cushion in the buy gate: a card that moves 2% at a time can be bought at a thinner discount than one that moves 12%. Needs at least 3 moves.', e: 'Moves of 3.82%, 3.75%, 1.78%, 4.98%, 1.40%, 1.18% → sorted 1.18, 1.40, 1.78, 3.75, 3.82, 4.98 → median = (1.78 + 3.75) / 2 = 2.77%.'},
  ts: {t: 'Slope 30d %/mo (Theil–Sen)', f: 'median over every pair of days (i, j) in the last 30 days of (ln P_j − ln P_i) / (j − i), then converted to % per month: (e^(slope × 30) − 1) × 100', m: 'The robust trend: the median of all pairwise slopes, so one spike day barely moves it, unlike a fitted line. It is the drift used in the buy gate (only negative drift counts against the sell price). Δ30d uses two endpoints; this uses all 465 pairs, so it is the steadier version of the same idea. Needs 10 points in the window.', e: '31 daily prices sliding from $48 to $42 → median pairwise slope −0.00413 per day → e^(−0.00413 × 30) − 1 = −11.7% per month. A plain regression gave −0.44%/day here; add one spike day and the two diverge.'},
  ec_price: {t: 'Price $ (eBay)', f: 'the anchor A once the card has any trimmed sales; until then the cheapest comparable listing', m: 'The card\'s market price from eBay alone, used by the $50–$150 default filter and the scam screen\'s price ratios. See Anchor $ for how it is built.', e: 'A = $94 → $94.'},
  ec_k: {t: 'Sold 30d (k)', f: 'count of comparable raw listings that sold in the last 30 days', m: 'The raw evidence behind λ. "Comparable" = ungraded, condition NM/LP or not stated, seller ≥ 98%. Sales only exist for listings the collector saw while they were live, so this starts at zero and grows.', e: '13 sales counted → k = 13.'},
  ec_d: {t: 'Days observed (D)', f: 'days since the first listing of this card was seen, capped at 30', m: 'The denominator for rates. A card first seen 5 days ago with 2 sales is 0.4/day, not 2/30.', e: 'First seen 19 days ago → D = 19.'},
  ec_lam: {t: 'λ — raw sales per day', f: '25th percentile of Gamma(k + ½, D)   (posterior for a Poisson rate with a flat prior)', m: 'Expected raw buyers per day, stated conservatively: the value the true rate exceeds three times out of four. With few sales it reads well below k/D on purpose; after ~20 sales it converges. It decides whether a card is liquid at your Confidence and Window, how long a credible copy may sit before it is ignored (1.6 ÷ λ days), and the Exp. days column.', e: 'k = 12, D = 18: k/D = 0.67/day, but λ = 0.56/day. k = 2, D = 10: k/D = 0.20 but λ = 0.11.'},
  ec_n: {t: 'Active (N)', f: 'number of comparable raw listings currently open for this card', m: 'The size of the book you would be competing in. Only comparable copies count (see Sold 30d).', e: '4 open NM/LP copies from ≥98% sellers → N = 4.'},
  ec_p: {t: 'p₁ p₂ p₃ — the book', f: 'the three cheapest comparable listings by total price (item + shipping); Best Offer copies ranked at 90% of ask', m: 'The three cheapest open copies as they are, before the credibility rules. A Best Offer listing at $122 is shown as $109.80 because that is roughly what it will actually take. The Floor column is the cheapest of these that is allowed to set the price; the Book popup greys the ones that are not.', e: 'Open copies $122 (BO), $123, $129 → p₁ = 109.80, p₂ = 123, p₃ = 129.'},
  ec_mu: {t: 'New/day (μ)', f: 'comparable listings first seen in the last 30 days ÷ D', m: 'The supply arrival rate — the counterpart of λ. Read it against λ in the In/out column.', e: '20 new comparable listings over 19 days → μ = 1.05/day.'},
  ec_dos: {t: 'Days of supply', f: 'N ÷ λ', m: 'How long the current book would take to clear at the observed demand. Under 7 = tight market, undercuts rare, price at pₙ − $1. Over 30 = glutted; sellers get impatient and the floor erodes — undercut by ~3% and do not count on rank 2.', e: 'N = 4, λ = 0.57 → 7.0 days.'},
  ec_io: {t: 'In/out (μ ÷ λ)', f: 'new listings per day ÷ sales per day', m: 'Above ~1.2 supply is piling up and the floor will be lower next week — your buy needs a bigger discount or a pass. Below ~0.8 supply is draining and prices firm. It is the eBay, raw-only version of PriceCharting\'s volume drift.', e: 'μ = 1.05, λ = 0.57 → 1.84: listings are arriving almost twice as fast as they sell.'},
  ec_smed: {t: 'Sold median $', f: 'median total (item + shipping) of the last 10 comparable raw sales', m: 'What buyers have been paying, as a plain median of the last ten. The anchor A does the same job more carefully (trimmed, recency-weighted); this stays as a quick reference and for the hot-card realized check. Best Offer sales are recorded at the listed price, so they may overstate by ~10%.', e: 'Same ten sales as above → $99.50.'},
  ec_s80: {t: 'Sold 80th percentile $', f: '80th percentile of the last 10 comparable sale totals', m: 'The top of the realistic range: only one sale in five went higher. Shown for reference; the Sell price is anchored on A, not on this.', e: 'Ten sales 92 … 110 → 80th percentile ≈ $104.'},
  ec_hrs: {t: 'Hours to sale', f: 'median hours from listing to sale over the last 10 comparable sales', m: 'How fast copies actually move. Under 48 h is one of the five hot-card checks. Resolution is the tracker\'s cadence (about an hour for fast sales).', e: 'Sale times 4, 9, 15, 22, 30, 41, 55 h → median 22 h.'},
  ec_st: {t: 'Sell-through %', f: 'of comparable listings first seen 7–37 days ago, the share that sold within 7 days', m: 'Uses listings old enough to have had a fair chance. ≥ 80% is a hot-card check. Needs at least 3 such listings.', e: '9 of 11 eligible listings sold within a week → 82%.'},
  ec_A: {t: 'Anchor A — what buyers pay', f: 'recency-weighted robust centre of the card\'s comparable sales in the last 30 days (60 if fewer than 5), after trimming outliers: weighted median under 8 sales, Hodges–Lehmann from 8', m: 'The card\'s price from what actually sold, with Lightly Played sales lifted to NM-equivalent, a 10-day half-life so last week counts more than three weeks ago, and two trims (Tukey fences, and a quarter-to-four-times-the-median band) that drop a Best Offer sale recorded at its ask or a copy that was really a different printing. Shows "thin" and the gate stays shut until a card has 5 sales behind it; hover for the count.', e: 'Sales 88, 90, 92, 94, 95, 96, 98, 99, 102, 105, 150 (BO at ask), 42 (wrong printing) → 150 and 42 trimmed → A = $94.'},
  ec_L: {t: 'Floor L — the cheapest credible copy', f: 'cheapest open comparable copy by effective price (Best Offer at 90%, LP lifted to NM-equivalent) that is not: watch/suspect tier, from a seller under 50 ratings or under the feedback bar, under 75% of A, or sat longer than 1.6 ÷ λ days (1–7)', m: 'The copy you must actually beat. A copy far under A is a deal or junk, not a price; a thin seller\'s copy is shown but never sets the price; a copy that has sat longer than this card\'s buyers allow has been passed over. The Book popup greys the copies the floor ignored.', e: 'Book $40, $70 (9 days old), $85 (3-feedback seller), $96 (Best Offer), $99 → floor = 96 × 0.9 = $86.40.'},
  ec_S: {t: 'Sell $ — the list price', f: 'min(L − $0.50, 0.95 × A), rounded down to .99; 0.93 × A with no credible floor; capped by the median of fast sales when the card has 8+ sales that sold within 48 h of listing', m: 'What you type into the listing, with free shipping. Just under the credible competition, never more than 5% under what buyers pay. Unsold at 36–48 h, cut to 0.90 × A. On the Raw Data tab this is computed per listing with that listing left out of the floor, because once you buy it, it is no longer competition.', e: 'L = $86.40, A = $94 → min(85.90, 89.30) = 85.90 → $84.99.'},
  ec_prob: {t: 'P(sale in window) %', f: '1 − e^(−λ × T), T = the Window box in days (rank 1)', m: 'The chance at least one buyer arrives inside your window while you are the cheapest credible copy. A card is liquid when this clears your Confidence; equivalently λ ≥ −ln(1 − Confidence) ÷ T.', e: 'λ = 0.99, 48 h → 1 − e^(−1.98) = 86%. λ = 0.56 → 67%, under a 70% bar: not liquid.'},
  ec_edays: {t: 'Expected days (at Confidence)', f: '−ln(1 − Confidence) ÷ λ', m: 'Days at the credible floor until a sale is as likely as your Confidence. The honest window for a card that is not liquid at your settings. Judge flips by profit per day, and this is the denominator.', e: 'λ = 0.56, 70% → 1.2 ÷ 0.56 = 2.1 days. λ = 0.1 → 12 days: not a flip card.'},
  ec_maxbuy: {t: 'Max buy $ (all-in)', f: 'net = Sell × (1 − 0.1325 × 1.065) − $0.40 − $4.50 − $0.30 = 0.8589 × Sell − $5.20;   max buy = net ÷ (1 + Margin)', m: 'The most you can pay in total — item + shipping + your sales tax — and still clear your Margin after eBay\'s fee (charged on the buyer\'s total including their tax), the per-order fee, the tracked label and supplies. Greyed "illiquid" when the card does not clear the liquidity rule; nothing on such a card can pass. A listing PASSes when its all-in is at or below this.', e: 'Sell $84.99 → net = 0.8589 × 84.99 − 5.20 = $67.80 → max buy = 67.80 ÷ 1.10 = $61.63: a $58 copy with free shipping ($61.62 with tax) passes.'},
  ec_net: {t: 'Net $ — proceeds at the sell price', f: '0.8589 × Sell − $5.20', m: 'What lands in your account if the card sells at Sell: the buyer total minus eBay\'s fee (on the total including the buyer\'s tax), the $0.40 per-order fee, the $4.50 tracked label and $0.30 of supplies. Depends on the anchors, not on Margin — Margin only decides how much of this you may spend on the buy.', e: 'Sell $84.99 → $67.80.'},
  ec_hot: {t: 'Hot', f: 'all five checks pass: k ≥ 5 · sell-through ≥ 80% · median hours to sale ≤ 48 · sold median ≥ 95% of the median ask · last 5 sales ≥ 97% of the 5 before', m: '"Candidate" means the history says demand outruns supply. "Confirmed" (✓) means the next three copies listed after the flag all sold within 48 hours — a test on data the checks never saw. A copy that sits more than 48 h resets the count. "fails n" tells you how many checks a card with enough sales is missing; hover for which.', e: 'A card with 13 sales, 82% sell-through, 22 h median, prices realized at ask and a flat trend is a candidate; three quick sales later it is confirmed.'},
  ec_book: {t: 'Book', f: 'the live data behind this card\'s row', m: 'Opens the competing listings (ranked, with links) and the recent sales with their time to sale. This is what to look at before every buy: whether the floor is a credible copy, whether the sales were Best Offer (recorded at ask, so possibly lower), and what condition sold.', e: ''},
  et_spm: {t: 'Sales/month (eBay)', f: 'raw sales recorded in the last 30 days, from the daily rollup', m: 'The eBay counterpart of PriceCharting\'s sales/yr, but raw-only and monthly. Today it equals Sold 30d; it lives in the Trends band because it is the series the Volume drift and the Trend chart are built on.', e: '13 sales in the last 30 days → 13.'},
  et_d7: {t: 'Δ7d % (eBay)', f: '(P_now ÷ P_7 days ago − 1) × 100, where P = trailing 7-day median of raw sale totals', m: 'The eBay price line is the median of what raw copies actually sold for in the last 7 days (needs 3 sales in the window, else blank). This is its one-week change. On thin cards it moves because different copies sold, not because the market moved — trust it on cards with dozens of sales.', e: 'P today $87.62, P a week ago $88.30 → −0.8%.'},
  et_d30: {t: 'Δ30d % (eBay)', f: '(P_now ÷ P_30 days ago − 1) × 100', m: 'One-month change of the 7-day median sale price. Needs 30 days of eBay history.', e: '$87.62 vs $91.00 → −3.7%.'},
  et_pos: {t: 'Range 90d % (eBay)', f: '(P_now − Low90) ÷ (High90 − Low90) × 100 over the 7-day median series', m: '0% = at the 90-day low of realized raw prices, 100% = at the high. Needs 60 days of history and 10 valid points.', e: 'Low $85.72, high $100.17, now $87.62 → 13%.'},
  et_vd: {t: 'Volume drift 30d (eBay)', f: 'sales in the last 30 days − sales in the 30 days before, and the % change', m: 'Month-over-month demand. PriceCharting\'s version compares against the same month a year earlier (seasonal); eBay history starts now, so this is month-over-month until a year has passed. Rising sales with a falling price = supply flood; rising sales with a rising price = real demand. Needs 60 days.', e: '55 sales vs 48 the month before → +7 (+14.6%).'},
  et_vol: {t: 'Volatility % (eBay)', f: 'median |ln(P_t ÷ P_t−1)| over days in the last 90 where the 7-day median changed; needs 3 changes', m: 'The typical day-to-day move of the realized price. Includes sampling noise on thin cards (which three copies sold), so it reads higher than PriceCharting\'s.', e: 'Daily moves of 0.3%, 0.4%, 0.5%, 1.1% → median 0.45%.'},
  et_ts: {t: 'Slope 30d %/mo (eBay)', f: 'Theil–Sen median of pairwise slopes of ln P over the last 30 days, shown as (e^(slope × 30) − 1) × 100', m: 'The robust trend of realized raw prices: the middle of all pairwise slopes, so one odd sale does not move it. Needs 30 days and 10 valid points. Negative = drifting down.', e: 'Median pairwise slope −0.00178/day → (e^(−0.0534) − 1) × 100 = −5.2%/mo.'},
  et_trend: {t: 'Trend (eBay)', f: 'the daily rollup behind the Trends band', m: 'Opens the chart: bars are raw sales per day, the blue line the 7-day median sale price, the green line the cheapest comparable ask that day, dashed lines the 90-day high/low and the Sell price. Same controls as the PriceCharting chart. The stats strip below it shows the trend columns and the pricing numbers side by side.', e: ''},
  er_listed: {t: 'Listed within (h)', f: 'hours since the listing was created on eBay', m: 'Deals on liquid cards are gone in minutes to hours, so the freshest rows matter most. The filter takes one number: type 2 to see only listings posted in the last 2 hours. The tab holds listings first seen in the last 24 hours; sold or ended ones stay visible with their status. The tab refreshes itself every minute while it is open, and rows that arrived since your last look are tinted green.', e: '0.3 = listed about 20 minutes ago.'},
  er_title: {t: 'eBay title', f: 'the seller\'s title, linked to the listing', m: 'What the parser matched to the catalog card in the first columns. Always read it before buying: variant words (reverse, 1st edition, shadowless), condition claims and anything odd. If the match looks wrong, that is a parser pattern to fix — the Unmatched button shows the ones it refused.', e: '"Charizard ex 199/165 Obsidian Flames SIR NM" → Charizard ex #199, Pokemon Obsidian Flames.'},
  er_item: {t: 'Item $ / Ship $', f: 'the listed price and the seller\'s shipping charge to your ZIP', m: 'Calculated shipping is estimated for the ZIP the collector was given. "free" means the seller folded shipping into the item.', e: '$118 + $4 shipping.'},
  er_total: {t: 'Total $', f: 'item + shipping', m: 'The buyer total, which is how everything else on the eBay tabs is measured (sold prices, the book, the Sell price).', e: '118 + 4 = $122.'},
  er_allin: {t: 'All-in $', f: 'item + shipping + item × Buy tax (the box at the top: 6.25% Massachusetts sales tax; 0 once eBay has approved your resale certificate)', m: 'What actually leaves your account. This is the number compared to Max buy. Set the Buy tax box to 0 only after the exemption is real: until then a listing the page calls PASS costs 6.25% more than it shows.', e: '118 + 4 + 7.38 = $129.38 at 6.25%; $122.00 at 0%.'},
  er_pc: {t: 'PC ungraded $', f: 'PriceCharting loose-price of the card this listing was matched to', m: 'PriceCharting\'s price for an ungraded copy of the matched card — the same number as Ungraded $ on the PriceCharting tab. It is on this tab for one job: catching wrong matches (see vs PC %). Every pricing number on the eBay tabs — Anchor, Sell, Max buy, Profit — still comes from eBay sales alone.', e: 'A listing matched to Charizard ex #199 shows $120.00 here, whatever the listing itself asks.'},
  er_vspc: {t: 'vs PC %', f: '(Total ÷ PC ungraded − 1) × 100', m: 'How far the listing sits from PriceCharting\'s price for the matched card. Under 40% of that price (−60% or lower) the verdict is "mismatch ↓"; over 300% (+200% or higher) it is "mismatch ↑". Either way the listing is treated as matched to the wrong card: never a hit, and left out of the book, the sold prices, λ and the trends. The rule is skipped when PriceCharting has fewer than 20 sales a year behind its price, when the set is under 30 days old, and on the cheap side for MP/HP copies. The numbers are constants at the top of the collector (PC_LOW, PC_HIGH, PC_MIN_SALES, PC_NEW_SET_D). Sort this column ascending to check the cheapest-looking matches by hand.', e: '$40 against $120 → −66.7% → mismatch ↓. $420 → +250.0% → mismatch ↑. $70 → −41.7% → judged normally.'},
  er_vs: {t: 'vs anchor %', f: '(total ÷ A − 1) × 100', m: 'How far the listing sits below (negative) or above what buyers pay for the card. A hit at a 10% margin needs roughly −31% from the Sell price, which is itself a few percent under A; under −55% the row says "review" instead.', e: 'Total $58, A $94 → −38.3%.'},
  er_profit: {t: 'Profit $ — for this listing', f: 'Net $ of the card − All-in $ of the listing', m: 'What you would clear buying this copy at its price and selling at this listing\'s Sell price (its floor computed without itself). Negative means the listing is above break-even. It is the same number whatever Margin you set; Margin only decides where PASS starts.', e: 'Net $67.80, all-in $61.62 → $6.18.'},
  er_roi: {t: 'ROI % — for this listing', f: 'Profit $ ÷ All-in $ × 100', m: 'Return on the cash tied up in this copy. PASS is exactly ROI ≥ your Margin setting. Sort the tab by this column descending to see the best buys first; judge against the card\'s Exp. days for profit per day.', e: '$6.18 ÷ $61.62 = 10.0% — at a 10% margin, so it just passes.'},
  er_time: {t: 'Time (h)', f: 'hours from listing to sale / end / gone; for an open listing, hours open so far (greyed)', m: 'How long this copy took to move, or how long it has been sitting. Read it against the card\'s Hrs to sale: a copy that sold in 3 hours on a card whose median is 40 says the price was low; an open copy past the median says it is priced above the buyers.', e: 'sold, 6.5 = it sold six and a half hours after listing. open, 30.2 = listed 30 hours ago and still for sale.'},
  lp: {t: 'LP correction (%)', f: 'per price tier: 1 − median over LP sales of (LP sale total ÷ median NM/unstated sale total of the same card within ±7 days)', m: 'How much less a Lightly Played copy sells for than a Near Mint one. It is used twice: inside the eBay Catalog every LP price is lifted to NM-equivalent (an LP sale at $83 counts as $94.32 at 12%), so Price, the floor and the Sell price are NM prices; and on Raw Data a listing that says LP has its sell price cut by it, so its Max buy, Profit, ROI and verdict are for a played copy. Not-stated listings are treated as NM. The number is read-only: it starts at 12% and is replaced by the measured ratio for a tier once that tier has 30 LP sales behind it (green outline); until then a tier uses the ratio measured across all tiers, and until that has 30 sales, the default. Hover a tier for where it stands. Pooled across all cards because one card never has enough LP sales to measure on its own; split by price tier because condition costs more on an expensive card.', e: 'A card sells NM at $95 and its LP copies at $83 → ratio 0.874 → 12.6% discount. If the <$100 tier has 41 such sales with a median of 0.90, that tier shows 10.0%.'},
  er_risk: {t: 'Risk — the scam screen', f: 'points: <50% of the card\'s price +4 · 50–65% +2 · 65–75% +1 (bands 5 points higher on $100+ cards) · seller feedback under 10 +3 · 10–49 +1 · unknown +1 · feedback % below the bar for its count +2 · one photo +1 · 3+ copies of a $75+ card +2 · photo also used by another seller +3 · no returns and under 65% +1 · delivery window over 10 days +1 · Top Rated Plus −2 · 500+ feedback at 99%+ −1. Score ≥ 5 = suspect, 3–4 = watch.', m: 'A cheap screen for the listings that are most likely not what they claim: a thin account, a deep discount, a borrowed photo, a stack of a card that does not come in stacks. No single signal decides — an honest new seller at a fair price scores 3 (watch) and stays. Suspect listings are kept out of every Catalog statistic (the book, sold prices, λ) so a fake copy cannot drag a card\'s price down, and they are hidden here behind the Show suspects box. Watch listings stay in the statistics but are never allowed to set the floor. A same-day burst of $75+ listings from a seller with no history pushes a watch listing to suspect. Hover the badge for the score and its reasons; the Scam screen button shows how past tiers and signals actually turned out.', e: '45% of the card\'s price (+4), 3 feedback (+3), one photo (+1), quantity 5 (+2) → 10, suspect. 80% of price, 5 feedback (+3) → 3, watch.'},
  er_photos: {t: 'Photos', f: 'number of photos on the listing', m: 'You need the front and the back to judge condition, so listings with fewer than 2 photos are left out of this tab (the count in the header line shows how many). Two photos is a minimum, not a promise — it is often the front plus a close-up, so still look. One photo is also a point on the scam score. The Catalog still counts these listings, because buyers buy from them and they are real competitors.', e: '4 = a front, a back and two close-ups. 1 = left out.'},
  er_verdict: {t: 'Verdict', f: 'PASS if all-in ≤ Max buy for this listing; otherwise the first reason it fails', m: 'Checks in order: "fewer than 2 photos" and "suspect" (hidden by default); "mismatch ↓ / ↑" (priced under 40% or over 300% of the PriceCharting price — treated as a wrong match, see vs PC %); "no sales yet" (no anchor); "too few sales (n)" (under 5 behind the anchor); "not liquid" (the card does not clear your Confidence inside your Window); "condition MP/HP"; the count-aware seller bar ("seller < 98%" for 100+ ratings, "< 95%" for 20–99); "review" (under 45% of A — check photos and seller first); then the price test against this listing\'s own Max buy, computed with the listing left out of the floor. A listing that passes on price has its item specifics read by the collector: "PASS ✓" = card number, name and set agree with the matched card; "PASS ID?" = not read yet or left blank by the seller; "ID conflict" = they describe another card (hover for what disagreed).', e: 'All-in $61.62 vs Max buy $61.63 → PASS. All-in $74.38 → "over max buy". Passing on price but listed as Language: Japanese → "ID conflict".'},
  er_cond: {t: 'Cond', f: 'condition words found in the title: NM, LP, MP, HP (n/s = not stated)', m: 'Only NM, LP and not-stated copies count as comparable. An LP listing gets the LP correction applied to its Max buy; not stated is treated as NM. MP/HP copies are shown but fail the gate, and they are excluded from the book and the sales history. The Condition chip in the filters shows or hides each of NM, LP and n/s (MP/HP rows appear only when all three are ticked).', e: '"Near Mint" or "NM" → NM; "lightly played" → LP.'},
  er_bo: {t: 'Offer', f: 'BO = the listing accepts Best Offers', m: 'You can usually get ~10% under the ask; the book ranks these copies at 90% for that reason. When one of these sells, the recorded price is the ask, so it may overstate the true sale.', e: ''},
  er_seller: {t: 'Seller fb / %', f: 'the seller\'s feedback count and positive percentage', m: 'The gate wants ≥ 98% (blank is tolerated). For raw cards, also prefer ≥ 50 feedback — a brand-new seller with a too-cheap card is the classic scam profile.', e: '512 feedback at 99.5%.'},
  er_status: {t: 'Status', f: 'open · sold · ended · gone · stale', m: 'open = still for sale at last check. sold = eBay reports a sale (the collector confirms every vanished listing with a lookup). ended = withdrawn or expired unsold. gone = no longer retrievable. stale = followed for 30 days without a sale. Sold and ended rows are the raw material for λ and the sold prices.', e: ''},
  trend: {t: 'Trend', f: 'one point per day from the site\'s own snapshots', m: 'Opens the card\'s daily history: sales/yr bars on the left axis, ungraded / retail buy / retail sell on the right, dashed lines for the 90-day high and low and the conservative sell estimate, a hover crosshair, all the statistics, and the buy-gate arithmetic for this card. The history starts the day the site went live and grows by one point each morning.', e: ''}
};
// what each eBay column is built from, and what is built from it (shown in the help popup)
const LINKS = {
  ec_k: ['eBay tracker outcomes', 'λ, Sell-thru, Hot'], ec_d: ['first sighting of the card', 'λ, New/day'],
  ec_n: ['open comparable listings', 'Days supply, the floor'],
  ec_p: ['open comparable listings, Best Offer haircut', 'the floor L (after the credibility rules), Price (when no sales yet)'],
  ec_mu: ['listings first seen in 30 d, Days obs.', 'In/out'], ec_smed: ['last 10 sales', 'Hot (realized check); reference only'],
  ec_s80: ['last 10 sales', 'reference only'], ec_hrs: ['last 10 sales', 'Hot; the future waiting-time λ (see README)'],
  ec_st: ['listings seen 7–37 d ago', 'Hot'],
  ec_lam: ['Sold 30d, Days obs.', 'liquidity (with Confidence and Window), the floor\'s stale rule, Days supply, In/out, P(sale in window), Exp. days'],
  ec_price: ['Anchor A (or p₁)', 'the $50–150 filter, the scam check'], ec_dos: ['Active, λ', 'reading only'], ec_io: ['New/day, λ', 'reading only'],
  ec_A: ['comparable sales, 30 d (60 if thin), trimmed and recency-weighted', 'Sell (the 95% cap), the floor (75% rule), vs anchor %, review band'],
  ec_L: ['open comparable copies, the scam tiers, seller feedback, λ', 'Sell'],
  ec_S: ['Floor L, Anchor A, fast-sale median, calibration', 'Net, Max buy, your list price'],
  ec_prob: ['λ, Window', 'liquid / illiquid'], ec_edays: ['λ, Confidence', 'reading only'],
  ec_maxbuy: ['Sell, Margin, fee, label, supplies', 'Verdict on the Raw Data tab'],
  ec_hot: ['Sold 30d, Sell-thru, Hrs to sale, Sold med vs asks, price trend', 'reading only'],
  et_spm: ['daily rollup of sales', 'Volume drift, the Trend chart'], et_d7: ['7-day median sale price series', 'reading only'], et_d30: ['7-day median sale price series', 'reading only'],
  et_pos: ['7-day median sale price series (90 d)', 'reading only'], et_vd: ['Sales/month now vs the month before', 'reading only'],
  et_vol: ['7-day median sale price series (90 d)', 'reading only'], et_ts: ['7-day median sale price series (30 d)', 'reading only'],
  er_allin: ['Item, Ship, your sales tax', 'Verdict, Profit'], er_verdict: ['All-in, this listing\'s Max buy, liquidity, Cond, Seller %, Anchor, vs PC %, the item-specifics check', '—'], er_vs: ['Total, Anchor A', 'reading only'],
  er_pc: ['PriceCharting daily snapshot (the matched card\'s ungraded price)', 'vs PC %'],
  er_vspc: ['Total, PC ungraded', 'Verdict (mismatch); whether the listing counts in the card\'s book, sold prices and λ'],
  ec_net: ['Sell, fee, label, supplies', 'Max buy, Profit $ on the Raw Data tab'],
  er_profit: ['Net $ of the card (LP-adjusted for LP listings), All-in $ of the listing', 'ROI %'], er_roi: ['Profit $, All-in $', 'reading only (PASS = ROI ≥ Margin)'],
  lp: ['LP sales vs NM/unstated sales of the same card, pooled by price tier', 'Catalog prices (NM-equivalent), Max buy / Profit / ROI / Verdict of LP listings'],
  er_time: ['listing time and outcome time', 'reading only; compare with Hrs to sale'],
  er_risk: ['price vs the card, seller feedback, photos, quantity, photo reuse, returns, delivery window', 'Verdict; suspect listings are excluded from the book, sold prices and λ'],
  er_photos: ['the listing', 'this tab (fewer than 2 = left out), the scam score'],
};
function openHelp(key) {
  const h = HELP[key]; if (!h) return;
  $('htitle').textContent = h.t;
  const L = LINKS[key];
  $('hbody').innerHTML = '<h4>Formula</h4><div class="formula">' + esc(h.f) + '</div><h4>What it means</h4><p>' + esc(h.m) + '</p>' + (h.e ? '<h4>Example</h4><p>' + esc(h.e) + '</p>' : '') +
    (L ? '<h4>Built from</h4><p>' + esc(L[0]) + '</p><h4>Feeds into</h4><p>' + esc(L[1]) + '</p>' : '');
  $('hov').classList.add('open');
}
$('readme-btn').addEventListener('click', () => { $('rbody').innerHTML = README; $('rov').classList.add('open'); });
$('rclose').addEventListener('click', () => $('rov').classList.remove('open'));
$('rov').addEventListener('click', e => { if (e.target === $('rov')) $('rov').classList.remove('open'); });
document.querySelectorAll('.help').forEach(b => b.addEventListener('click', e => { e.stopPropagation(); openHelp(b.dataset.h); }));
$('hclose').addEventListener('click', () => $('hov').classList.remove('open'));
$('hov').addEventListener('click', e => { if (e.target === $('hov')) $('hov').classList.remove('open'); });

