const README = `
<h3>1. What the three tabs are</h3>
<p><b>PriceCharting Catalog</b> is the card list with PriceCharting's prices and the trend columns built from this site's own daily snapshots. <b>eBay Catalog</b> is the same card list with numbers computed <i>only</i> from eBay: every raw (ungraded) single listed in the last 30 days, matched to a card by its title, followed until it sells or ends. <b>eBay Raw Data</b> is the listings themselves — every matched raw single first seen in the last 24 hours, with the buy verdict. The eBay side is fed by a collector running around the clock on a small rented machine: it reads eBay's newest listings every minute, re-checks older ones for sales, and publishes every couple of minutes; the two eBay tabs pick the new data up on their own, and Raw Data tints rows that arrived since your last look.</p>
<p><b>All eBay prices are buyer totals: item + shipping.</b> That is what the buyer paid and what you compare against, and because you list with free shipping, P₄₈ is literally the number you type into the listing.</p>

<h3>2. Reading the eBay Catalog: three bands</h3>
<p><span class="legend"><span class="l-obs">Observed</span></span> columns are independent inputs measured on eBay — counts, the book of competing copies, sold prices. <span class="legend"><span class="l-rate">Rates</span></span> are computed from Observed only (λ, Price, Days supply, In/out). <span class="legend"><span class="l-dec">Decisions</span></span> depend on λ, the book, and your <b>Confidence</b> and <b>Margin</b> settings at the top — change those and only the amber band moves. Every header's <b>?</b> shows the formula, an example, what the column is built from and what it feeds.</p>

<p>A fourth band, <span class="legend"><span class="l-tr">Trends</span></span>, applies the PriceCharting tab's trend formulas to eBay's own realized prices: the price line is the median of raw sale totals over a trailing 7-day window (blank with fewer than 3 sales in the window), and the Trend button charts it with sales per day and the cheapest ask. These fill in on the same schedule as the PriceCharting versions — 7, 30 and 60 days after the collector started — and are noisier on thin cards, where the median moves because different copies sold rather than because the market did.</p>

<h3>3. The Poisson walkthrough — will it sell within 48 hours at this price?</h3>
<p>Take a card with <b>k = 30</b> observed raw sales in <b>D = 30</b> days, a book of comparable open copies at <b>$96, $99, $104, $110</b>, and a sold 80th percentile of <b>$101</b>.</p>
<p><b>Step 1 — demand rate λ.</b> The naive rate is k ÷ D = 1.00/day. A rate estimated from a count is uncertain, so the site uses the 25th percentile of the posterior Gamma(k + ½, D): the value the true rate beats three times in four.</p>
<div class="formula">λ = (30.5 ÷ 30) × [1 − 1/(9·30.5) + z/(3√30.5)]³   with z = −0.6745
  = 1.0167 × [1 − 0.0036 − 0.0407]³ = 1.0167 × 0.8728 = 0.887 sales/day</div>
<p>With only 8 sales in 12 days the same formula gives 0.53 against a naive 0.67 — the haircut is bigger when the evidence is thinner. That is the point.</p>
<p><b>Step 2 — buyers in the window are Poisson.</b> If buyers arrive independently at a steady average rate, the number arriving in T days has mean m = λT and P(exactly j) = e<sup>−m</sup> m<sup>j</sup> / j!. For 48 hours, m = 0.887 × 2 = 1.774 and e<sup>−1.774</sup> = 0.1695:</p>
<table><thead><tr><th>j buyers</th><th class="num">P(exactly j)</th><th class="num">P(at least j)</th></tr></thead><tbody>
<tr><td>0</td><td class="num">0.1695</td><td class="num">1.000</td></tr>
<tr><td>1</td><td class="num">1.774 × 0.1695 = 0.3009</td><td class="num">0.831</td></tr>
<tr><td>2</td><td class="num">1.774² ÷ 2 × 0.1695 = 0.2669</td><td class="num">0.530</td></tr>
<tr><td>3</td><td class="num">1.774³ ÷ 6 × 0.1695 = 0.1579</td><td class="num">0.263</td></tr></tbody></table>
<p><b>Step 3 — depth n.</b> n₄₈ is the largest n with P(at least n buyers) ≥ Confidence (70%). P(≥1) = 83% clears it, P(≥2) = 53% does not, so <b>n₄₈ = 1</b>: over two days you can count on one buyer, so you must be the cheapest copy. For 24 hours m = 0.887 and P(≥1) = 59% &lt; 70%, so <b>n₂₄ = 0</b>: no 24-hour price exists for this card. Its P(≤24h) column reads 59%, and Exp. days = −ln(1 − 0.70) ÷ λ = 1.204 ÷ 0.887 = 1.4 days to reach 70%. n is capped at 3 because buyers are not perfectly price-ordered deeper than that. Neither price is offered until the card has at least <b>three observed sales</b>: with one or two, a lucky evening can produce a λ that clears the bar on its own, so until the third sale the row shows only the Window price.</p>
<p><b>Step 4 — the price.</b> P₄₈ = p<sub>n</sub> − $1 with n = 1, so p₁ = $96 gives <b>P₄₈ = $95</b>, capped at the sold 80th percentile ($101) — fine. Had that $96 copy been a Best Offer listing it would rank at 96 × 0.9 = $86.40 and P₄₈ would be $85.40: you undercut what it will actually take, not what it asks. At $95 you sit at rank 1 and the chance of a sale within 48 hours is P(≥1) = <b>83%</b>, above the 70% bar because n = 1 cleared it with room to spare.</p>
<p><b>Step 5 — back to max buy.</b> No P₂₄ here, so the gate uses P₄₈:</p>
<div class="formula">net = 95 × (1 − 0.1325 × 1.065) − 0.30 − 4.50 = 95 × 0.8589 − 4.80 = $76.79
max buy = 76.79 ÷ (1 + 0.15) = $66.78 all-in   (≈ $59 item price with $4 shipping and 6.25% tax)</div>
<p><b>What it means.</b> If the last 30 days are a fair guide, listing this card at $95 free shipping gets it sold within two days about four times in five, and paying up to $66.78 all-in leaves a 15% margin after eBay's fee (charged on the buyer's total including their sales tax), the fixed fee and tracked shipping out. It is a model estimate, not a promise: buyers bunch on evenings and weekends, someone can undercut you mid-window, and a listing with bad photos is not "credible" at any rank. The conservative λ absorbs some of that; calibration (section 6) measures the rest.</p>

<h3>4. What to do with the numbers</h3>
<ul>
<li><b>Buy</b> when a listing's all-in (item + shipping + your tax) is at or below Max buy — the Raw Data tab says PASS. Then read the title, the photos and the seller before you click; open the card's <b>Book</b> to see the copies you would compete with and how the recent sales went.</li>
<li><b>List</b> at P₄₈, free shipping, Best Offer on with auto-accept at P₂₄ (or ~3% under P₄₈ when there is no P₂₄). Bargain hunters take it on day one at P₂₄; patient buyers pay P₄₈.</li>
<li>If it has not moved after 48 hours, cut to P₂₄. After another window, it was mispriced or the card slowed — take the small loss and note why.</li>
<li>Past 48 hours each extra day adds about 1% to the price and about 11% to your capital cycle. Two days is the planned window; anything longer only makes sense when there is nothing to buy anyway.</li>
</ul>

<h3>5. The Confidence and Margin boxes</h3>
<p><b>Only show hits</b> filters the Raw Data tab to listings whose verdict is PASS — the ones where buying at the asking price and selling at the gate's price clears your Margin. <b>Confidence</b> is the probability the P₂₄ / P₄₈ prices are set for. Raise it and n falls, prices fall, Net and Max buy fall: you are demanding a surer sale. 70% is the default because a missed window costs a day, not a loss. <b>Margin</b> is the profit required on all-in cost; it moves Max buy and the PASS threshold and nothing else. <b>Net $</b> on the Catalog is what you clear at the gate's sell price; <b>Profit $</b> and <b>ROI %</b> on the Raw Data tab apply that to each listing's all-in cost, so sorting Raw Data by ROI shows the best buys first. Both boxes are remembered in this browser and change nothing in the collector.</p>

<h3>6. Calibration — of the price, not the rate</h3>
<p>λ is left exactly as the data says. What gets checked is the price claim: "a listing at P₄₈ sells within 48 hours 70% of the time." When a listing first appears, the collector records the P₄₈ the model would have set for its card that moment, and how far above or below it the listing was actually priced. Two days later the tracker knows whether it sold. Pooling every listing that entered the buyable part of the book (rank 1–3) gives a table: realized 48-hour sell-through by price offset from P₄₈.</p>
<table><thead><tr><th>Offset from model P₄₈</th><th class="num">Listings</th><th class="num">Sold ≤ 48 h</th><th class="num">Realized</th></tr></thead><tbody>
<tr><td>−10% to −5%</td><td class="num">73</td><td class="num">52</td><td class="num">71%</td></tr>
<tr><td>−5% to −2%</td><td class="num">35</td><td class="num">14</td><td class="num">40%</td></tr>
<tr><td>−2% to +2%</td><td class="num">43</td><td class="num">9</td><td class="num">21%</td></tr></tbody></table>
<p>In that (invented) table the realized curve crosses 70% at about −7%: listings at the model's P₄₈ sold far less than 70% of the time, and you had to be ~7% cheaper to get it. The site then shifts P₄₈ by that offset — the <b>Calibration</b> box at the top shows the measured offset and how many outcomes it rests on, and applies it once there are at least 150 outcomes with 25 in each bucket around the crossing. The same is done for P₂₄ with 24-hour outcomes. Until then the Poisson price stands as is. The best calibration data of all is your own listings: keep a ledger of card, buy price, list price, sold price and hours to sale from your first flip.</p>

<h3>7. When demand exceeds supply — the fix to apply later</h3>
<p><b>The signature:</b> Sell-thru ≥ 80%, Days supply under 3, Hrs to sale short, few Active copies. Copies vanish within hours of appearing.</p>
<p><b>The problem:</b> on such a card the count of sales is capped by the count of copies listed. Five copies in a month means at most five sales, so λ from counts comes out low — the model says 60% when reality is closer to 95%, prices too cautiously, and you pass on deals or list too cheap on exactly the cards where you could hold out. The error is in the safe direction, which is why it is tolerated for now.</p>
<p><b>The fix:</b> use time-to-sale, which supply cannot cap. If copies typically sell 20 hours after listing, buyers are arriving at least every 20 hours whether or not a copy exists. For an exponential wait the median is ln 2 ÷ λ, so</p>
<div class="formula">λ_wait = ln 2 ÷ (median hours to sale ÷ 24)     e.g. 20 h → 0.693 ÷ 0.833 = 0.83 sales/day</div>
<p>even if only five copies were ever listed. Because not every sold copy sat at rank 1, this still understates demand a little, which keeps it conservative.</p>
<p><b>What to do:</b> after two or three weeks, look at the Hot cards (candidate or confirmed) and compare their λ column with ln 2 ÷ (Hrs to sale ÷ 24). If the waiting-time number is consistently and clearly higher on the confirmed ones, switch the collector to use λ_wait whenever the signature above is present (Sell-thru ≥ 80% and Days supply &lt; 3, with at least 5 sales) — it is a few lines in compute_stats() in ebay_sweep.py. Do not switch before the data shows the gap; changing a model before you can check it is how you end up trusting the wrong number.</p>

<h3>8. Hot cards</h3>
<p>Five checks from history: k ≥ 5, Sell-thru ≥ 80%, median Hrs to sale ≤ 48, sales realized at ≥ 95% of the median ask, and the last five sales not more than 3% below the five before. Passing all five makes a <b>candidate</b>. The next three copies listed after the flag are then watched: all three selling within 48 hours makes it <b>confirmed</b> (a test on data the checks never saw); one sitting longer resets the count. Confirmed cards are the ones where you can pay close to full Max buy, because the exit is nearly certain — and where deals will be scarcest.</p>

<h3>9. Condition and the LP correction</h3>
<p>Demand and supply are condition-blind: a buyer who takes a Lightly Played copy is a real buyer, and an LP copy in the book is a real competitor. Price is not. So the Catalog counts NM, LP and unstated listings alike, but lifts every LP price to NM-equivalent (an LP sale at $83 is treated as $94.32 at a 12% correction) before computing the sold median, the book and P₄₈ — the Catalog's prices are NM prices. On Raw Data the correction runs the other way: a listing that says LP has its sell price cut by it, so its Max buy, Profit, ROI and verdict are for a played copy (hover Max buy to see the NM figure). Not-stated listings are treated as NM. MP and HP are a different market and stay out entirely.</p>
<p>The correction is read-only and shown next to Margin for three price tiers (under $100, $100–150, $150+), because condition costs more on an expensive card. It starts at 12% and is replaced by the measured LP-to-NM ratio — pooled across every card, since no single card has enough LP sales — once a tier has 30 LP sales behind it; a tier without enough sales uses the ratio measured across all tiers, and until that exists, the default. Hover a tier to see where it stands.</p>

<h3>10. The scam screen</h3>
<p>Scam listings hurt twice: they show up as the best "deals", and while they are live they sit in the card's book as the cheapest copy and drag P₄₈ and Max buy down for everyone. eBay removes them eventually, but only after the damage. So every listing gets a score from cheap signals — how far under the card's price it is, the seller's feedback count and whether their percentage clears the bar for that count, one photo, a stack of copies of a card that does not come in stacks, a photo already used by another seller, no returns on a cheap listing, a long delivery window, with credit for Top Rated Plus and long-established sellers. No single signal decides: an honest new seller at a fair price scores 3 and stays. Score 5 or more is <b>suspect</b>: kept out of every statistic and hidden on Raw Data behind the Show suspects box. 3–4 is <b>watch</b>: in the statistics, badged, but never used alone as a card's cheapest copy. Raw Data also leaves out any listing with fewer than 2 photos, because condition cannot be judged without the back — the Catalog still counts those listings, since buyers buy from them.</p>
<p>The score is calibrated from outcomes, like the price: every closed listing keeps the score it had, and the Scam screen button tabulates how each tier and each signal turned out — sold, ended, or "gone" (pulled before its end date, which is what eBay does to scams). A signal that fires mostly on listings that later vanish is earning its points; one that fires on listings that sold normally is catching honest sellers and gets cut. Thresholds are adjusted by hand from that table, not fitted automatically.</p>

<h3>11. What the model does not see</h3>
<p>Promoted listings outrank you at equal price. Auctions ending in the window soak up buyers. Best Offer sales are recorded at the ask, so sold prices can run ~10% high. Titles the parser cannot resolve to one card are skipped, not guessed — the Unmatched button on the Raw Data tab lists them. And the Browse API only reports sales for listings that were seen while live, so history starts the day the collector was switched on and grows forward.</p>
`;

/* ---------------- Column help ---------------- */
const pct = v => (v * 100).toFixed(2).replace(/\.?0+$/, '') + '%';
const HELP = {
  card: {t: 'Card', f: 'PriceCharting product name = card name + [variant] + #number', m: 'Each printing is its own row with its own prices: a plain card, its [Reverse Holo], [Holo], [1st Edition] or [Shadowless] version are different products. The name links to the PriceCharting page.', e: '"Spinarak #6" and "Spinarak [Ditto] #6" are the same card number in the same set, at $0.83 and $15.24 — a seller who lists only "Spinarak 6/78" may not know which one they have.'},
  set: {t: 'Set', f: 'PriceCharting console-name', m: 'The set the card was printed in, in PriceCharting\'s naming. The table and the set dropdown are ordered by each set\'s release date.', e: '"Pokemon Base Set" (1999) sorts before "Pokemon Jungle" (1999-06) before "Pokemon Evolving Skies" (2021).'},
  num: {t: '#', f: 'the number after "#" at the end of the product name', m: 'The card\'s collector number within its set — printed on the card as 4/102 or 010/078. Set + number + variant uniquely identify a card. Kept as text because modern sets use prefixes (TG01, SV001, GG05).', e: 'Base Set #4 is Charizard; Jungle #4 is Kangaskhan. Same number, different cards.'},
  released: {t: 'Released', f: 'PriceCharting release-date', m: 'The card\'s original release date. Cards without one show "—" and their set is ordered by the earliest dated card in it.', e: '1999-01-09 for Base Set; 2022-07-01 for Pokémon Go.'},
  sales: {t: 'Sales/yr', f: 'PriceCharting sales-volume = units sold in the trailing 12 months, ALL grades combined', m: 'A liquidity measure — but it counts raw and graded sales together. For cheap modern cards almost nothing is graded, so it ≈ raw sales. For vintage cards graded sales can be most of it, so it overstates how often a raw copy sells. Use the Trend popup\'s "raw sale every N days" for the raw-only view.', e: 'Ivysaur #2 (1998 KFC): 45/yr in this column, but PriceCharting\'s page shows ungraded ≈ 12/yr, Grade 8 ≈ 12, PSA 10 ≈ 12, Grade 7 = 6, Grade 9 = 3. 12+6+12+3+12 ≈ 45.'},
  ungraded: {t: 'Ungraded $', f: 'PriceCharting loose-price', m: 'The market price of an ungraded copy — a trailing average of recent raw sales (mostly eBay). This is the anchor: every other number is measured against it. It only moves when new raw sales land, so a slow card\'s price can sit unchanged for weeks. It blends all conditions; a near-mint copy sells closer to the Grade 7–8 price.', e: 'If the anchor is $42.00 and a listing is $27.99 + $4 shipping, the listing is 76% of anchor before tax — then fees, shipping out and drift decide whether that is a deal (see Trend popup).'},
  d7: {t: 'Δ7d %', f: '(P_today − P_7_days_ago) / P_7_days_ago × 100', m: '"Did something just happen." On a slow card this is usually one sale landing, so pair it with a Sales/yr floor before trusting it. Sort descending for cards that just jumped (sell candidates), ascending for cards that just dropped.', e: '$42.00 today, $42.50 a week ago → (42.00 − 42.50) / 42.50 = −1.2%.'},
  d30: {t: 'Δ30d %', f: '(P_today − P_30_days_ago) / P_30_days_ago × 100', m: 'The core trend number and the one to sort by. Read it with Δ7d and the slope: 30d down but 7d flat and the slope flattening is a card that may be settling; all of them down is a card still falling. A drop is either mispricing (opportunity) or news (a reprint, a rotation) — the number cannot tell which.', e: '$42.00 today, $48.00 thirty days ago → (42.00 − 48.00) / 48.00 = −12.5%.'},
  pos: {t: 'Range 90d %', f: '(P_today − Low_90d) / (High_90d − Low_90d) × 100', m: 'Where today\'s price sits between its 90-day low (0%) and high (100%). Two cards can both be −12% over 30 days: one falling back from a spike (still at 85% of its range) and one making new lows (5%). Different bets. Ignore it when the range is tiny, and remember a low position during a steady decline is a falling knife — it is only a signal once the 30-day trend has flattened. Needs 60 days of history.', e: 'Low $38.00, high $52.00, today $42.00 → (42 − 38) / (52 − 38) = 4 / 14 = 29%.'},
  vd: {t: 'Volume drift 30d', f: 'Sales/yr_today − Sales/yr_30_days_ago   (and as % of the earlier value)', m: 'Because Sales/yr is a trailing 365-day count, the 30-day difference equals (sales in the last 30 days) minus (sales in the 30-day window that just fell out of the year — roughly the same month a year ago). So a positive number means this month beat the same month last year: a year-over-year demand signal that is automatically seasonally matched. It counts all grades, so on vintage cards it is mostly a graded-market signal, and small counts are noise — +2 on a base of 40 means nothing. Sorting and the range filter use the percent. Rising volume with a rising price is real heat; rising volume with a falling price is a supply flood (a reprint hitting the market), the pattern where a "bargain" keeps getting cheaper.', e: '210 today, 196 thirty days ago → +14 sales, +14 / 196 = +7.1%.'},
  vol: {t: 'Volatility %', f: 'median of |ln(P_t / P_t−1)| over the days the price moved in the last 90 days', m: 'The typical size of a move when the price moves. The median ignores a single wild day, which a standard deviation would not. It sizes the safety cushion in the buy gate: a card that moves 2% at a time can be bought at a thinner discount than one that moves 12%. Needs at least 3 moves.', e: 'Moves of 3.82%, 3.75%, 1.78%, 4.98%, 1.40%, 1.18% → sorted 1.18, 1.40, 1.78, 3.75, 3.82, 4.98 → median = (1.78 + 3.75) / 2 = 2.77%.'},
  ts: {t: 'Slope 30d %/mo (Theil–Sen)', f: 'median over every pair of days (i, j) in the last 30 days of (ln P_j − ln P_i) / (j − i), then converted to % per month: (e^(slope × 30) − 1) × 100', m: 'The robust trend: the median of all pairwise slopes, so one spike day barely moves it, unlike a fitted line. It is the drift used in the buy gate (only negative drift counts against the sell price). Δ30d uses two endpoints; this uses all 465 pairs, so it is the steadier version of the same idea. Needs 10 points in the window.', e: '31 daily prices sliding from $48 to $42 → median pairwise slope −0.00413 per day → e^(−0.00413 × 30) − 1 = −11.7% per month. A plain regression gave −0.44%/day here; add one spike day and the two diverge.'},
  ec_price: {t: 'Price $ (eBay)', f: 'median of the card\'s last 10 raw sale totals (item + shipping); until it has 3 sales, the cheapest comparable listing', m: 'The card\'s market price from eBay alone — what buyers actually paid, not what sellers ask. It is the number the $50–$150 default filter works on, and the yardstick for a listing\'s "vs price %".', e: 'Last 10 sale totals 92, 95, 96, 98, 99, 100, 101, 103, 105, 110 → median = (99 + 100) / 2 = $99.50.'},
  ec_k: {t: 'Sold 30d (k)', f: 'count of comparable raw listings that sold in the last 30 days', m: 'The raw evidence behind λ. "Comparable" = ungraded, condition NM/LP or not stated, seller ≥ 98%. Sales only exist for listings the collector saw while they were live, so this starts at zero and grows.', e: '13 sales counted → k = 13.'},
  ec_d: {t: 'Days observed (D)', f: 'days since the first listing of this card was seen, capped at 30', m: 'The denominator for rates. A card first seen 5 days ago with 2 sales is 0.4/day, not 2/30.', e: 'First seen 19 days ago → D = 19.'},
  ec_lam: {t: 'λ — raw sales per day', f: '25th percentile of Gamma(k + ½, D)   (posterior for a Poisson rate with a flat prior)', m: 'Expected raw buyers per day, stated conservatively: the value the true rate exceeds three times out of four. With few sales it reads well below k/D on purpose; after ~20 sales it converges. Everything in the pricing columns runs off this number.', e: 'k = 13, D = 19: k/D = 0.68/day, but λ = 0.57/day (25th percentile). k = 2, D = 10: k/D = 0.20 but λ = 0.11.'},
  ec_n: {t: 'Active (N)', f: 'number of comparable raw listings currently open for this card', m: 'The size of the book you would be competing in. Only comparable copies count (see Sold 30d).', e: '4 open NM/LP copies from ≥98% sellers → N = 4.'},
  ec_p: {t: 'p₁ p₂ p₃ — the book', f: 'the three cheapest comparable listings by total price (item + shipping); Best Offer copies ranked at 90% of ask', m: 'The prices you would have to beat. A Best Offer listing at $122 is shown as $109.80 because that is roughly what it will actually take. Depth pricing sits one dollar under pₙ.', e: 'Open copies $122 (BO), $123, $129 → p₁ = 109.80, p₂ = 123, p₃ = 129.'},
  ec_mu: {t: 'New/day (μ)', f: 'comparable listings first seen in the last 30 days ÷ D', m: 'The supply arrival rate — the counterpart of λ. Read it against λ in the In/out column.', e: '20 new comparable listings over 19 days → μ = 1.05/day.'},
  ec_dos: {t: 'Days of supply', f: 'N ÷ λ', m: 'How long the current book would take to clear at the observed demand. Under 7 = tight market, undercuts rare, price at pₙ − $1. Over 30 = glutted; sellers get impatient and the floor erodes — undercut by ~3% and do not count on rank 2.', e: 'N = 4, λ = 0.57 → 7.0 days.'},
  ec_io: {t: 'In/out (μ ÷ λ)', f: 'new listings per day ÷ sales per day', m: 'Above ~1.2 supply is piling up and the floor will be lower next week — your buy needs a bigger discount or a pass. Below ~0.8 supply is draining and prices firm. It is the eBay, raw-only version of PriceCharting\'s volume drift.', e: 'μ = 1.05, λ = 0.57 → 1.84: listings are arriving almost twice as fast as they sell.'},
  ec_smed: {t: 'Sold median $', f: 'median total (item + shipping) of the last 10 comparable raw sales', m: 'What buyers have actually been paying. It is the 24-hour price for a hot card whose book is empty, and the ceiling sanity check for everything else. Best Offer sales are recorded at the listed price, so they may overstate by ~10%.', e: 'Same ten sales as above → $99.50.'},
  ec_s80: {t: 'Sold 80th percentile $', f: '80th percentile of the last 10 comparable sale totals', m: 'The top of the realistic range: only one sale in five went higher. P₄₈ is capped here, and it is the list price for a ten-day sale on a hot card.', e: 'Ten sales 92 … 110 → 80th percentile ≈ $104.'},
  ec_hrs: {t: 'Hours to sale', f: 'median hours from listing to sale over the last 10 comparable sales', m: 'How fast copies actually move. Under 48 h is one of the five hot-card checks. Resolution is the tracker\'s cadence (about an hour for fast sales).', e: 'Sale times 4, 9, 15, 22, 30, 41, 55 h → median 22 h.'},
  ec_st: {t: 'Sell-through %', f: 'of comparable listings first seen 7–37 days ago, the share that sold within 7 days', m: 'Uses listings old enough to have had a fair chance. ≥ 80% is a hot-card check. Needs at least 3 such listings.', e: '9 of 11 eligible listings sold within a week → 82%.'},
  ec_n24: {t: 'n₂₄ / n₄₈ — depth', f: 'largest n (≤ 3) such that P(Poisson(λ·T) ≥ n) ≥ 70%, with T = 1 day for n₂₄ and 2 days for n₄₈; 0 until the card has 3 sales', m: 'How many buyers you can count on in the window, at 70% confidence. Held at 0 while the card has fewer than 3 sales: two sales on a card seen for two days give a λ that clears the bar by luck, not by evidence, so until the third sale only the Window price is offered. The buyer who shows up takes the cheapest credible copy, so n is how deep in the book you can sit and still be reached: n = 2 means "even if one copy sells ahead of me, the second buyer is mine." n = 0 means fewer than one buyer is likely in that window — no 24/48-hour price exists; see Exp. days. Capped at 3 because buyers are not perfectly price-ordered that deep.', e: 'λ = 2.5: P(≥2 buyers in a day) = 71% → n₂₄ = 2; P(≥3) = 46% → not 3. λ = 0.57: P(≥1 in a day) = 43% → n₂₄ = 0; P(≥1 in two days) = 68% → n₄₈ = 0 (just short of 70%).'},
  ec_p24: {t: 'P₂₄ — 24-hour price', f: 'pₙ₂₄ − $1 when the book has at least n₂₄ comparable copies; otherwise the sold median (capped at p₁ − $1); needs 3 sales', m: 'The buyer total (free shipping) at which the card sells within 24 hours with 70% probability. It is the auto-accept floor for Best Offer, and the price the Max buy column is derived from. Blank when n₂₄ = 0, including every card with fewer than 3 sales.', e: 'λ = 2.5 → n₂₄ = 2; book [96, 99, 104, 110] → P₂₄ = 99 − 1 = $98.'},
  ec_p48: {t: 'P₄₈ — 48-hour price', f: 'pₙ₄₈ − $1 when the book has at least n₄₈ copies; otherwise the sold 80th percentile (capped at p₁ − $1); never below P₂₄, never above the sold 80th percentile; needs 3 sales', m: 'The list price. Blank until the card has 3 sales (see n₂₄ / n₄₈). Two days contain two full evening peaks, so this is the planned window; you list here with Best Offer on and auto-accept at P₂₄. Past 48 h each extra day adds ~1% to the price and ~11% to the capital cycle, which is a losing trade.', e: 'λ = 2.5 → n₄₈ = 3 (P(≥3 buyers in 2 days) = 88%); book [96, 99, 104, 110] → P₄₈ = 104 − 1 = $103; capped at the 80th percentile of sales if that is lower.'},
  ec_pw: {t: 'Window $ — honest-window price', f: 'p₁ − $1 (or the sold median with an empty book), capped at the sold 80th percentile', m: 'For cards where no 24/48-hour price exists (n = 0, which includes every card with fewer than 3 sales): the price at which you are the cheapest copy, to be sold within Exp. days. Max buy falls back to this so slow cards still get a gate.', e: 'Book [110 (BO → 99), 123, 129] → window price = 99 − 1 = $98, expected sale in 2.1 days.'},
  ec_prob: {t: 'P(sale ≤ 24 h) %', f: '1 − e^(−λ)   (rank 1, one day)', m: 'The chance at least one buyer arrives within a day while you are the cheapest copy. Above 85% is what a confirmed hot card looks like without pricing for it.', e: 'λ = 2.0 → 1 − e⁻² = 86%. λ = 0.57 → 43%.'},
  ec_edays: {t: 'Expected days (70%)', f: '−ln(1 − 0.70) ÷ λ = 1.2 ÷ λ', m: 'Days at rank 1 until a sale is 70% likely. The honest window when 24/48-hour selling is not on offer. Judge flips by profit per day, and this is the denominator.', e: 'λ = 0.57 → 1.2 ÷ 0.57 = 2.1 days. λ = 0.1 → 12 days: not a flip card.'},
  ec_maxbuy: {t: 'Max buy $ (all-in)', f: 'net = P × (1 − 0.1325 × 1.065) − $0.30 − $4.50;   max buy = net ÷ 1.15   where P = P₂₄, else P₄₈, else Window $', m: 'The most you can pay in total — item + shipping + your sales tax — and still clear a 15% margin after eBay\'s fee (charged on the buyer\'s total including their tax), the fixed fee and tracked shipping out. The column notes which price it came from. A listing PASSes when its all-in is at or below this.', e: 'P₂₄ = $98 → net = 98 × 0.859 − 4.80 = $79.37 → max buy = 79.37 ÷ 1.15 = $69.02, i.e. about a $61 item price with $4 shipping and 6.25% tax.'},
  ec_net: {t: 'Net $ — proceeds at the sell price', f: 'P × (1 − 0.1325 × 1.065) − $0.30 − $4.50   where P = P₂₄, else P₄₈, else Window $ (the basis noted on Max buy)', m: 'What lands in your account if the card sells at the gate\'s price: the buyer total minus eBay\'s fee (charged on the total including the buyer\'s tax), the fixed fee and tracked shipping out. Depends on Confidence (through P) but not on Margin — Margin only decides how much of this you may spend on the buy.', e: 'P₄₈ = $95 → 95 × 0.8589 − 4.80 = $76.79.'},
  ec_hot: {t: 'Hot', f: 'all five checks pass: k ≥ 5 · sell-through ≥ 80% · median hours to sale ≤ 48 · sold median ≥ 95% of the median ask · last 5 sales ≥ 97% of the 5 before', m: '"Candidate" means the history says demand outruns supply. "Confirmed" (✓) means the next three copies listed after the flag all sold within 48 hours — a test on data the checks never saw. A copy that sits more than 48 h resets the count. "fails n" tells you how many checks a card with enough sales is missing; hover for which.', e: 'A card with 13 sales, 82% sell-through, 22 h median, prices realized at ask and a flat trend is a candidate; three quick sales later it is confirmed.'},
  ec_book: {t: 'Book', f: 'the live data behind this card\'s row', m: 'Opens the competing listings (ranked, with links) and the recent sales with their time to sale. This is what to look at before every buy: whether the floor is a credible copy, whether the sales were Best Offer (recorded at ask, so possibly lower), and what condition sold.', e: ''},
  et_spm: {t: 'Sales/month (eBay)', f: 'raw sales recorded in the last 30 days, from the daily rollup', m: 'The eBay counterpart of PriceCharting\'s sales/yr, but raw-only and monthly. Today it equals Sold 30d; it lives in the Trends band because it is the series the Volume drift and the Trend chart are built on.', e: '13 sales in the last 30 days → 13.'},
  et_d7: {t: 'Δ7d % (eBay)', f: '(P_now ÷ P_7 days ago − 1) × 100, where P = trailing 7-day median of raw sale totals', m: 'The eBay price line is the median of what raw copies actually sold for in the last 7 days (needs 3 sales in the window, else blank). This is its one-week change. On thin cards it moves because different copies sold, not because the market moved — trust it on cards with dozens of sales.', e: 'P today $87.62, P a week ago $88.30 → −0.8%.'},
  et_d30: {t: 'Δ30d % (eBay)', f: '(P_now ÷ P_30 days ago − 1) × 100', m: 'One-month change of the 7-day median sale price. Needs 30 days of eBay history.', e: '$87.62 vs $91.00 → −3.7%.'},
  et_pos: {t: 'Range 90d % (eBay)', f: '(P_now − Low90) ÷ (High90 − Low90) × 100 over the 7-day median series', m: '0% = at the 90-day low of realized raw prices, 100% = at the high. Needs 60 days of history and 10 valid points.', e: 'Low $85.72, high $100.17, now $87.62 → 13%.'},
  et_vd: {t: 'Volume drift 30d (eBay)', f: 'sales in the last 30 days − sales in the 30 days before, and the % change', m: 'Month-over-month demand. PriceCharting\'s version compares against the same month a year earlier (seasonal); eBay history starts now, so this is month-over-month until a year has passed. Rising sales with a falling price = supply flood; rising sales with a rising price = real demand. Needs 60 days.', e: '55 sales vs 48 the month before → +7 (+14.6%).'},
  et_vol: {t: 'Volatility % (eBay)', f: 'median |ln(P_t ÷ P_t−1)| over days in the last 90 where the 7-day median changed; needs 3 changes', m: 'The typical day-to-day move of the realized price. Includes sampling noise on thin cards (which three copies sold), so it reads higher than PriceCharting\'s.', e: 'Daily moves of 0.3%, 0.4%, 0.5%, 1.1% → median 0.45%.'},
  et_ts: {t: 'Slope 30d %/mo (eBay)', f: 'Theil–Sen median of pairwise slopes of ln P over the last 30 days, shown as (e^(slope × 30) − 1) × 100', m: 'The robust trend of realized raw prices: the middle of all pairwise slopes, so one odd sale does not move it. Needs 30 days and 10 valid points. Negative = drifting down.', e: 'Median pairwise slope −0.00178/day → (e^(−0.0534) − 1) × 100 = −5.2%/mo.'},
  et_trend: {t: 'Trend (eBay)', f: 'the daily rollup behind the Trends band', m: 'Opens the chart: bars are raw sales per day, the blue line the 7-day median sale price, the green line the cheapest comparable ask that day, dashed lines the 90-day high/low and P₄₈. Same controls as the PriceCharting chart. The stats strip below it shows the trend columns and the pricing numbers side by side.', e: ''},
  er_listed: {t: 'Listed within (h)', f: 'hours since the listing was created on eBay', m: 'Deals on liquid cards are gone in minutes to hours, so the freshest rows matter most. The filter takes one number: type 2 to see only listings posted in the last 2 hours. The tab holds listings first seen in the last 24 hours; sold or ended ones stay visible with their status. The tab refreshes itself every minute while it is open, and rows that arrived since your last look are tinted green.', e: '0.3 = listed about 20 minutes ago.'},
  er_title: {t: 'eBay title', f: 'the seller\'s title, linked to the listing', m: 'What the parser matched to the catalog card in the first columns. Always read it before buying: variant words (reverse, 1st edition, shadowless), condition claims and anything odd. If the match looks wrong, that is a parser pattern to fix — the Unmatched button shows the ones it refused.', e: '"Charizard ex 199/165 Obsidian Flames SIR NM" → Charizard ex #199, Pokemon Obsidian Flames.'},
  er_item: {t: 'Item $ / Ship $', f: 'the listed price and the seller\'s shipping charge to your ZIP', m: 'Calculated shipping is estimated for the ZIP the collector was given. "free" means the seller folded shipping into the item.', e: '$118 + $4 shipping.'},
  er_total: {t: 'Total $', f: 'item + shipping', m: 'The buyer total, which is how everything else on the eBay tabs is measured (sold prices, the book, P₂₄).', e: '118 + 4 = $122.'},
  er_allin: {t: 'All-in $', f: 'item + shipping + item × 6.25% (MA sales tax)', m: 'What actually leaves your account. This is the number compared to Max buy.', e: '118 + 4 + 7.38 = $129.38.'},
  er_vs: {t: 'vs price %', f: '(total ÷ card price − 1) × 100', m: 'How far the listing sits below (negative) or above the card\'s eBay price. It is the mispricing at a glance; the verdict is the same idea after fees and margin.', e: 'Total $98, card price $122 → −19.7%.'},
  er_profit: {t: 'Profit $ — for this listing', f: 'Net $ of the card − All-in $ of the listing', m: 'What you would clear buying this copy at its price and selling at the card\'s gate price. Negative means the listing is above break-even. Depends on Confidence through Net, and on nothing else — it is the same number whatever Margin you set; Margin only decides where PASS starts.', e: 'Net $76.79, all-in $61.20 → $15.59.'},
  er_roi: {t: 'ROI % — for this listing', f: 'Profit $ ÷ All-in $ × 100', m: 'Return on the cash tied up in this copy. PASS is exactly ROI ≥ your Margin setting. Sort the tab by this column descending to see the best buys first; judge against the card\'s Exp. days for profit per day.', e: '$15.59 ÷ $61.20 = 25.5% — above a 15% margin, so it passes.'},
  er_time: {t: 'Time (h)', f: 'hours from listing to sale / end / gone; for an open listing, hours open so far (greyed)', m: 'How long this copy took to move, or how long it has been sitting. Read it against the card\'s Hrs to sale: a copy that sold in 3 hours on a card whose median is 40 says the price was low; an open copy past the median says it is priced above the buyers.', e: 'sold, 6.5 = it sold six and a half hours after listing. open, 30.2 = listed 30 hours ago and still for sale.'},
  lp: {t: 'LP correction (%)', f: 'per price tier: 1 − median over LP sales of (LP sale total ÷ median NM/unstated sale total of the same card within ±7 days)', m: 'How much less a Lightly Played copy sells for than a Near Mint one. It is used twice: inside the eBay Catalog every LP price is lifted to NM-equivalent (an LP sale at $83 counts as $94.32 at 12%), so Price, the book and P₄₈ are NM prices; and on Raw Data a listing that says LP has its sell price cut by it, so its Max buy, Profit, ROI and verdict are for a played copy. Not-stated listings are treated as NM. The number is read-only: it starts at 12% and is replaced by the measured ratio for a tier once that tier has 30 LP sales behind it (green outline); until then a tier uses the ratio measured across all tiers, and until that has 30 sales, the default. Hover a tier for where it stands. Pooled across all cards because one card never has enough LP sales to measure on its own; split by price tier because condition costs more on an expensive card.', e: 'A card sells NM at $95 and its LP copies at $83 → ratio 0.874 → 12.6% discount. If the <$100 tier has 41 such sales with a median of 0.90, that tier shows 10.0%.'},
  er_risk: {t: 'Risk — the scam screen', f: 'points: <50% of the card\'s price +4 · 50–65% +2 · 65–75% +1 (bands 5 points higher on $100+ cards) · seller feedback under 10 +3 · 10–49 +1 · unknown +1 · feedback % below the bar for its count +2 · one photo +1 · 3+ copies of a $75+ card +2 · photo also used by another seller +3 · no returns and under 65% +1 · delivery window over 10 days +1 · Top Rated Plus −2 · 500+ feedback at 99%+ −1. Score ≥ 5 = suspect, 3–4 = watch.', m: 'A cheap screen for the listings that are most likely not what they claim: a thin account, a deep discount, a borrowed photo, a stack of a card that does not come in stacks. No single signal decides — an honest new seller at a fair price scores 3 (watch) and stays. Suspect listings are kept out of every Catalog statistic (the book, sold prices, λ) so a fake copy cannot drag a card\'s price down, and they are hidden here behind the Show suspects box. Watch listings stay in the statistics but are never used alone as a card\'s cheapest copy. A same-day burst of $75+ listings from a seller with no history pushes a watch listing to suspect. Hover the badge for the score and its reasons; the Scam screen button shows how past tiers and signals actually turned out.', e: '45% of the card\'s price (+4), 3 feedback (+3), one photo (+1), quantity 5 (+2) → 10, suspect. 80% of price, 5 feedback (+3) → 3, watch.'},
  er_photos: {t: 'Photos', f: 'number of photos on the listing', m: 'You need the front and the back to judge condition, so listings with fewer than 2 photos are left out of this tab (the count in the header line shows how many). Two photos is a minimum, not a promise — it is often the front plus a close-up, so still look. One photo is also a point on the scam score. The Catalog still counts these listings, because buyers buy from them and they are real competitors.', e: '4 = a front, a back and two close-ups. 1 = left out.'},
  er_verdict: {t: 'Verdict', f: 'PASS if all-in ≤ Max buy; otherwise the first reason it fails', m: 'PASS = it clears the gate on price alone — still read the title, photos and seller before buying. "fewer than 2 photos" and "suspect" come first (those listings are hidden by default). "too cheap – scam check" fires under 50% of the card price. "seller < 98%" / "seller < 95%" is the count-aware feedback bar: sellers with 100+ ratings need 98%, 20–99 need 95%, under 20 the percentage is ignored (one negative at 20 ratings reads 95%). "no sales yet" = the card has listings but no observed sales, so there is no λ and no Max buy yet.', e: 'All-in $129.38 vs Max buy $77.08 → "over max buy".'},
  er_cond: {t: 'Cond', f: 'condition words found in the title: NM, LP, MP, HP (n/s = not stated)', m: 'Only NM, LP and not-stated copies count as comparable. An LP listing gets the LP correction applied to its Max buy; not stated is treated as NM. MP/HP copies are shown but fail the gate, and they are excluded from the book and the sales history. The Condition chip in the filters shows or hides each of NM, LP and n/s (MP/HP rows appear only when all three are ticked).', e: '"Near Mint" or "NM" → NM; "lightly played" → LP.'},
  er_bo: {t: 'Offer', f: 'BO = the listing accepts Best Offers', m: 'You can usually get ~10% under the ask; the book ranks these copies at 90% for that reason. When one of these sells, the recorded price is the ask, so it may overstate the true sale.', e: ''},
  er_seller: {t: 'Seller fb / %', f: 'the seller\'s feedback count and positive percentage', m: 'The gate wants ≥ 98% (blank is tolerated). For raw cards, also prefer ≥ 50 feedback — a brand-new seller with a too-cheap card is the classic scam profile.', e: '512 feedback at 99.5%.'},
  er_status: {t: 'Status', f: 'open · sold · ended · gone · stale', m: 'open = still for sale at last check. sold = eBay reports a sale (the collector confirms every vanished listing with a lookup). ended = withdrawn or expired unsold. gone = no longer retrievable. stale = followed for 30 days without a sale. Sold and ended rows are the raw material for λ and the sold prices.', e: ''},
  trend: {t: 'Trend', f: 'one point per day from the site\'s own snapshots', m: 'Opens the card\'s daily history: sales/yr bars on the left axis, ungraded / retail buy / retail sell on the right, dashed lines for the 90-day high and low and the conservative sell estimate, a hover crosshair, all the statistics, and the buy-gate arithmetic for this card. The history starts the day the site went live and grows by one point each morning.', e: ''}
};
// what each eBay column is built from, and what is built from it (shown in the help popup)
const LINKS = {
  ec_k: ['eBay tracker outcomes', 'λ, Sell-thru, Hot'], ec_d: ['first sighting of the card', 'λ, New/day'],
  ec_n: ['open comparable listings', 'Days supply, n → P₂₄/P₄₈ (the book must be at least n deep)'],
  ec_p: ['open comparable listings, Best Offer haircut', 'P₂₄, P₄₈, Window, Price (when no sales yet)'],
  ec_mu: ['listings first seen in 30 d, Days obs.', 'In/out'], ec_smed: ['last 10 sales', 'Price, P₂₄ fallback, Hot (realized check)'],
  ec_s80: ['last 10 sales', 'P₄₈ fallback and cap, Window cap'], ec_hrs: ['last 10 sales', 'Hot; the future waiting-time λ (see README)'],
  ec_st: ['listings seen 7–37 d ago', 'Hot'],
  ec_lam: ['Sold 30d, Days obs.', 'n₂₄, n₄₈, Days supply, In/out, P(≤24h), Exp. days'],
  ec_price: ['Sold med (or p₁)', 'the $50–150 filter, vs price %, the scam check'], ec_dos: ['Active, λ', 'reading only'], ec_io: ['New/day, λ', 'reading only'],
  ec_n24: ['λ, Confidence', 'P₂₄, P₄₈'], ec_p24: ['n₂₄, the book, Sold med, calibration', 'Max buy (first choice), Best Offer auto-accept'],
  ec_p48: ['n₄₈, the book, Sold 80%, calibration', 'Max buy (second choice), your list price'], ec_pw: ['p₁ or Sold med, Sold 80%', 'Max buy (last resort)'],
  ec_prob: ['λ', 'reading only'], ec_edays: ['λ, Confidence', 'reading only'],
  ec_maxbuy: ['P₂₄ / P₄₈ / Window, Margin, fee, shipping', 'Verdict on the Raw Data tab'],
  ec_hot: ['Sold 30d, Sell-thru, Hrs to sale, Sold med vs asks, price trend', 'reading only'],
  et_spm: ['daily rollup of sales', 'Volume drift, the Trend chart'], et_d7: ['7-day median sale price series', 'reading only'], et_d30: ['7-day median sale price series', 'reading only'],
  et_pos: ['7-day median sale price series (90 d)', 'reading only'], et_vd: ['Sales/month now vs the month before', 'reading only'],
  et_vol: ['7-day median sale price series (90 d)', 'reading only'], et_ts: ['7-day median sale price series (30 d)', 'reading only'],
  er_allin: ['Item, Ship, your sales tax', 'Verdict, Profit'], er_verdict: ['All-in, Max buy, Cond, Seller %, Card price', '—'], er_vs: ['Total, Card price', 'reading only'],
  ec_net: ['P₂₄ / P₄₈ / Window, fee, shipping out', 'Max buy, Profit $ on the Raw Data tab'],
  er_profit: ['Net $ of the card (LP-adjusted for LP listings), All-in $ of the listing', 'ROI %'], er_roi: ['Profit $, All-in $', 'reading only (PASS = ROI ≥ Margin)'],
  lp: ['LP sales vs NM/unstated sales of the same card, pooled by price tier', 'Catalog prices (NM-equivalent), Max buy / Profit / ROI / Verdict of LP listings'],
  er_time: ['listing time and outcome time', 'reading only; compare with Hrs to sale'],
  er_risk: ['price vs the card, seller feedback, photos, quantity, photo reuse, returns, delivery window', 'Verdict; suspect listings are excluded from the book, sold prices and λ'],
  er_photos: ['the listing', 'this tab (fewer than 2 = left out), the scam score'],
};
function openHelp(key) {
  const h = HELP[key]; if (!h) return;
  $('htitle').textContent = h.t;
  const L = LINKS[key];
  $('hbody').innerHTML = '<h4>Formula</h4><div class="formula">' + esc(h.f) + '</div><h4>What it means</h4><p>' + esc(h.m) + '</p>' + (h.e ? '<h4>Example</h4><p>' + esc(h.e) + '</p>' : '') +
    (L ? '<h4>Built from</h4><p>' + esc(L[0]) + '</p><h4>Feeds into</h4><p>' + esc(L[1]) + '</p>' : '');
  $('hov').classList.add('open');
}
$('readme-btn').addEventListener('click', () => { $('rbody').innerHTML = README; $('rov').classList.add('open'); });
$('rclose').addEventListener('click', () => $('rov').classList.remove('open'));
$('rov').addEventListener('click', e => { if (e.target === $('rov')) $('rov').classList.remove('open'); });
document.querySelectorAll('.help').forEach(b => b.addEventListener('click', e => { e.stopPropagation(); openHelp(b.dataset.h); }));
$('hclose').addEventListener('click', () => $('hov').classList.remove('open'));
$('hov').addEventListener('click', e => { if (e.target === $('hov')) $('hov').classList.remove('open'); });

