const README = {
pc: `
<h3>1. What this tab is</h3>
<p>The card list with <b>PriceCharting's</b> prices: one row per printing (a card, its reverse holo and its 1st edition are separate rows with separate prices), ordered by each set's release date. The site rebuilds it every morning from PriceCharting's price file. Nothing on this tab comes from eBay.</p>
<p><b>Ungraded $</b> is PriceCharting's price for a raw copy - a trailing average of recent raw sales, all conditions blended, so a near-mint copy usually sells for more. It only moves when new sales land, so a slow card's price can sit unchanged for weeks. <b>Sales/yr</b> counts every grade together, raw and graded; on vintage cards most of it can be graded sales.</p>

<h3>2. The trend columns</h3>
<p>These are built from this site's own daily snapshots of the PriceCharting price, one point per card per morning, so they fill in as history accumulates: a column stays blank until it has the days it needs. The line under the tabs says how many days of history exist.</p>
<ul>
<li><b>&Delta;7d %</b> and <b>&Delta;30d %</b> - the change against the price 7 and 30 days ago. On a slow card a 7-day move is usually one sale landing.</li>
<li><b>Range 90d %</b> - where today's price sits between its 90-day low (0%) and high (100%). Needs 60 days.</li>
<li><b>Volume drift 30d</b> - Sales/yr today minus Sales/yr 30 days ago. Because Sales/yr is a trailing year, this compares the last 30 days with the same month a year earlier.</li>
<li><b>Volatility %</b> - the typical size of a move when the price moves, over 90 days. Needs at least 3 moves.</li>
<li><b>Slope 30d %/mo</b> - the robust 30-day trend (the median of every pairwise slope), so one spike day barely moves it. Needs 10 points.</li>
</ul>
<p>Every header's <b>?</b> gives the formula and a worked example. The <b>Trend</b> button on a row opens that card's chart.</p>

<h3>3. Using it</h3>
<p>Type in the search box for a card or a set, pick a set from the dropdown, and narrow with the min-max chips above the table (for instance Sales/yr at least 100 and Ungraded $ from 40 to 500). Click a header to sort; the eye on a header hides that column. Sort &Delta;30d descending for cards that have risen, ascending for cards that have fallen - the number cannot tell a mispricing from news such as a reprint.</p>

<h3>4. How the eBay tabs use these prices</h3>
<p>The eBay tabs work out their own prices from eBay sales and use PriceCharting in only two places. A listing priced under 40% or over 300% of the card's Ungraded price is treated as a wrong match and can never be a hit. And for a card with fewer than 5 recorded eBay sales, the Ungraded price stands in for eBay's so the listing can be shown as a <b>lead</b>. Both are explained in the eBay Raw Data README.</p>
`,
ec: `
<h3>1. What this tab is</h3>
<p>The same card list as the PriceCharting tab, with numbers computed <i>only</i> from eBay: every raw (ungraded) single matched to a card by its title and followed for its first 2 days (section 4 says why 2). The eBay side is fed by a collector running around the clock on a small rented machine: it reads eBay's newest listings every minute, re-checks older ones for sales, and publishes every couple of minutes; the two eBay tabs pick the new data up on their own, and Raw Data tints rows that arrived since your last look.</p>
<p><b>All eBay prices are buyer totals: item + shipping.</b> That is what the buyer paid and what you compare against, and because you list with free shipping, the Sell price is literally the number you type into the listing.</p>
<p>The amber Decisions band (Sell, Max buy, liquid) depends on four settings - Confidence, Window, Margin and Buy tax. Those boxes now sit on the <b>eBay Raw Data</b> tab, under the tabs; what you set there applies here too.</p>

<h3>2. Reading the table: three bands</h3>
<p><span class="legend"><span class="l-obs">Observed</span></span> columns are independent inputs measured on eBay — counts, the book of competing copies, sold prices. <span class="legend"><span class="l-rate">Rates</span></span> are computed from Observed only (λ, Price, Days supply, In/out). <span class="legend"><span class="l-dec">Decisions</span></span> depend on the two anchors (sections 3 and 4) and your <b>Confidence</b>, <b>Window</b> and <b>Margin</b> settings on the eBay Raw Data tab — change those and only the amber band moves. Every header's <b>?</b> shows the formula, an example, what the column is built from and what it feeds.</p>

<p>A fourth band, <span class="legend"><span class="l-tr">Trends</span></span>, applies the PriceCharting tab's trend formulas to eBay's own realized prices: the price line is the median of raw sale totals over a trailing 7-day window (blank with fewer than 3 sales in the window), and the Trend button charts it with sales per day and the cheapest ask. These fill in on the same schedule as the PriceCharting versions — 7, 30 and 60 days after the collector started — and are noisier on thin cards, where the median moves because different copies sold rather than because the market did.</p>

<h3>3. The sell price — two anchors, worked through</h3>
<p>The Sell price answers one question: <i>what do I list at so this card goes inside my window without giving money away?</i> Two numbers answer it, and the lower one wins.</p>
<p><b>Anchor A — what buyers actually pay.</b> Take the card's comparable sales over the last 30 days (60 if there are fewer than 5), with Lightly Played sales lifted to NM-equivalent. Example, twelve sales: $88, 90, 92, 94, 95, 96, 98, 99, 102, 105, plus a <b>$150</b> Best Offer sale recorded at its asking price and a <b>$42</b> copy that was really a different printing. Two trims throw the junk out: anything outside the Tukey fences (1.5 × the interquartile range beyond the middle half) and anything outside a quarter to four times the median. $150 and $42 both go. The ten that remain are weighted by recency (a sale 10 days old counts half as much as one today, 20 days old a quarter) and combined with a robust centre: a weighted median under 8 sales, the Hodges–Lehmann estimator from 8 up — the median of all pairwise averages, the same device as the Theil–Sen slope on the trend columns, about 15% less noisy than a plain median and still immune to a few bad points. Here <b>A = $94</b>. The Anchor column shows "thin" and the gate stays shut until a card has 5 sales behind A.</p>
<p><b>Floor L — the cheapest copy you must actually beat.</b> Now the open copies. Say the book is $40, $70, $85, $96, $99, $104. Not all of these are competition:</p>
<ul>
<li>the <b>$40</b> copy is under 75% of A — it is a deal to buy or a copy with something wrong, not a price to match;</li>
<li>the <b>$85</b> copy is from a 3-feedback seller (watch tier) — shown, never a price-setter; the same for any seller under 50 ratings or under the feedback bar;</li>
<li>the <b>$70</b> copy has sat 9 days on a card that sells every other day — a credible copy on this card is gone within about 1.6 ÷ λ = 3 days, so buyers have looked at it and passed;</li>
<li>the <b>$96</b> copy takes Best Offers, so it ranks at 90%: <b>$86.40</b>.</li>
</ul>
<p>The credible floor is <b>L = $86.40</b>. Then</p>
<div class="formula">Sell = min(L − $0.50, 0.95 × A) = min(85.90, 89.30) = 85.90 → rounded down to <b>$84.99</b></div>
<p>With no credible copy at all, Sell = 0.93 × A. When a card has 8 or more sales that sold within 48 hours of listing, their median caps the price too — the price that provably sells fast. The old rule, "cheapest copy minus a dollar", would have listed this card at $39 because of the $40 copy; that is why the Decisions band was wrong whenever the book had junk in it, which on a 4-day-old collector was most of the time.</p>

<h3>4. Will it sell inside the window? — the liquidity rule</h3>
<p>Buyers for a card arrive at a rate λ (sales per day, stated conservatively as the 25th percentile of the Gamma posterior, so a card with 12 sales in 18 days reads 0.56 rather than 0.67). If they arrive at a steady average rate, the chance that at least one shows up inside T days is 1 − e<sup>−λT</sup>. Demanding that chance be at least your Confidence turns into a rate the card has to clear:</p>
<div class="formula">λ needed = −ln(1 − Confidence) ÷ T days
48 h at 70% → 0.60/day     48 h at 80% → 0.80/day     48 h at 90% → 1.15/day     72 h at 70% → 0.40/day</div>
<p>A card that clears it (and, once measured, has a 48-hour sell-through of at least 25%) is <b>liquid</b>; otherwise its Max buy is greyed "illiquid" and nothing on it can pass. This is the single biggest lever on how many cards are eligible: 48 hours at 80% needs roughly 24 sales a month; 72 hours at 70% needs 12. The Window and Confidence boxes let you see that trade-off instead of inheriting it — one extra day of holding against an 8–14 day cash cycle (see the eBay Raw Data README) is cheap. The rest of the old Poisson machinery — pricing off the second-cheapest copy because two buyers are expected — is gone: it assumed buyers take strictly the cheapest copy, which eBay's photos, feedback and promoted placement make untrue.</p>
<p><b>The 2-day rule (since October 6).</b> You only flip cards that sell inside your window, and the 5,000 eBay calls a day could not follow every listing to day 10: about 3,270 listings disappeared a day and only about 1,370 could be looked up, so half the outcomes were never read. A listing is now followed for its <b>first 2 days only</b>. If it disappears in that time, one lookup says whether it sold. If it is still for sale after 2 days it is <b>stale</b>: it did not sell inside the window, and what becomes of it later is not asked. Two exceptions keep the picture honest. A card's cheapest copies stay in the book whatever their age, and are still checked on cards that have a price, because on a busy card the copy that sells is often an older one that has become the cheapest. And suspects get one last lookup at day 6, because eBay often pulls a scam listing days after it went up. What this changes in the numbers: sales of copies that sat more than 2 days are no longer counted (apart from those cheapest copies), so Sold 30d and λ run lower and the prices lean towards what sells quickly; Sell-through is now the share sold within 48 hours, with the liquidity bar moved from 50% within 7 days to 25% within 48 hours (on the day of the switch, the fast cards that passed the old bar had between 25% and 50% of those same listings sold within 48 hours; 25% keeps every one of them); Active counts copies listed in the last 2 days plus each card's few cheapest older ones; a price drop on a listing older than 2 days is no longer seen.</p>

<h3>5. Calibration — of the price, not the rate</h3>
<p>λ is left exactly as the data says. What gets checked is the price claim. When a listing first appears, the collector records the Sell price the model would have set for its card at that moment, and how far above or below it the listing was priced. Two days later the tracker knows whether it sold. Pooling every listing that entered the buyable top of its book gives a table: realized 48-hour sell-through by offset from Sell. If listings at the model's price sell far less than 70% of the time and it takes being 7% cheaper to get there, Sell shifts by 7% — the <b>Calibration</b> box shows the measured offset and how many outcomes it rests on, and applies it once there are at least 150 outcomes with 25 in each bucket around the crossing. The Scam screen button on the Raw Data tab also shows <b>how fast cheap listings go</b>: closed listings grouped by their price relative to A when first seen, with how many sold within 1, 6, 24 and 48 hours. That table answers the question the whole system turns on — whether listings at 60–70% of the anchor are gone within an hour (the scanner must be faster) or sit for days (they were cheap for a reason).</p>

<h3>6. When demand exceeds supply — the fix to apply later</h3>
<p><b>The signature:</b> Sell-thru ≥ 35% within 48 hours, Days supply under 3, Hrs to sale short, few Active copies. Copies vanish within hours of appearing.</p>
<p><b>The problem:</b> on such a card the count of sales is capped by the count of copies listed. Five copies in a month means at most five sales, so λ from counts comes out low — the model says 60% when reality is closer to 95%, prices too cautiously, and you pass on deals or list too cheap on exactly the cards where you could hold out. The error is in the safe direction, which is why it is tolerated for now.</p>
<p><b>The fix:</b> use time-to-sale, which supply cannot cap. If copies typically sell 20 hours after listing, buyers are arriving at least every 20 hours whether or not a copy exists. For an exponential wait the median is ln 2 ÷ λ, so</p>
<div class="formula">λ_wait = ln 2 ÷ (median hours to sale ÷ 24)     e.g. 20 h → 0.693 ÷ 0.833 = 0.83 sales/day</div>
<p>even if only five copies were ever listed. Because not every sold copy sat at rank 1, this still understates demand a little, which keeps it conservative.</p>
<p><b>What to do:</b> after two or three weeks, look at the Hot cards (candidate or confirmed) and compare their λ column with ln 2 ÷ (Hrs to sale ÷ 24). If the waiting-time number is consistently and clearly higher on the confirmed ones, switch the collector to use λ_wait whenever the signature above is present (Sell-thru ≥ 35% within 48 hours and Days supply &lt; 3, with at least 5 sales) — it is a few lines in compute_stats() in ebay_sweep.py. Do not switch before the data shows the gap; changing a model before you can check it is how you end up trusting the wrong number.</p>

<h3>7. Hot cards</h3>
<p>Five checks from history: k ≥ 5, 48-hour Sell-thru ≥ 35%, median Hrs to sale ≤ 48, sales realized at ≥ 95% of the median ask, and the last five sales not more than 3% below the five before. Passing all five makes a <b>candidate</b>. The next three copies listed after the flag are then watched: all three selling within 48 hours makes it <b>confirmed</b> (a test on data the checks never saw); one sitting longer resets the count. Confirmed cards are the ones where you can pay close to full Max buy, because the exit is nearly certain — and where deals will be scarcest.</p>

<h3>8. Condition and the LP correction</h3>
<p>Demand and supply are condition-blind: a buyer who takes a Lightly Played copy is a real buyer, and an LP copy in the book is a real competitor. Price is not. So the Catalog counts NM, LP and unstated listings alike, but lifts every LP price to NM-equivalent (an LP sale at $83 is treated as $94.32 at a 12% correction) before computing the anchor, the floor and the Sell price — the Catalog's prices are NM prices. On Raw Data the correction runs the other way: a listing that says LP has its sell price cut by it, so its Max buy, Profit, ROI and verdict are for a played copy (hover Max buy to see the NM figure). Not-stated listings are treated as NM. MP and HP are a different market and stay out entirely.</p>
<p>The correction is read-only and shown with the settings on the eBay Raw Data tab, for three price tiers (under $100, $100–150, $150+), because condition costs more on an expensive card. It starts at 12% and is replaced by the measured LP-to-NM ratio — pooled across every card, since no single card has enough LP sales — once a tier has 30 LP sales behind it; a tier without enough sales uses the ratio measured across all tiers, and until that exists, the default. Hover a tier to see where it stands.</p>

<h3>9. What the model does not see</h3>
<p>Promoted listings outrank you at equal price. Auctions ending in the window soak up buyers. Best Offer sales are recorded at the ask, so sold prices can run ~10% high. Titles the parser cannot resolve to one card are skipped, not guessed — the Unmatched button on the Raw Data tab lists them. And the Browse API only reports sales for listings that were seen while live, so history starts the day the collector was switched on and grows forward.</p>
`,
er: `
<h3>1. What this tab is</h3>
<p>The listings themselves: every raw (ungraded) single matched to a card and first seen in the last 24 hours, newest first, each with the buy verdict for that listing. The eBay side is fed by a collector running around the clock on a small rented machine: it reads eBay's newest listings every minute, re-checks older ones for sales, and publishes every couple of minutes; the two eBay tabs pick the new data up on their own, and Raw Data tints rows that arrived since your last look.</p>
<p><b>All eBay prices are buyer totals: item + shipping.</b> That is what the buyer paid and what you compare against, and because you list with free shipping, the Sell price is literally the number you type into the listing.</p>
<p>The bar under the tabs holds the settings that judge these listings (section 3). They only exist on this tab now, and they also drive the Sell, Max buy and liquid columns of the eBay Catalog.</p>

<h3>2. The buy gate</h3>
<p>What you keep from a sale at price S, listed with free shipping:</p>
<div class="formula">net = S × (1 − 0.1325 × 1.065) − $0.40 − $4.50 − $0.30 = 0.8589 × S − $5.20
   eBay's 13.25% is charged on the buyer's total including their sales tax; $0.40 per order; $4.50 tracked label; $0.30 sleeve, top loader and mailer
Max buy = net ÷ (1 + Margin)</div>
<p>On the example card: net = 0.8589 × 84.99 − 5.20 = <b>$67.80</b>; at a 10% margin Max buy = <b>$61.63</b> all-in. All-in is what leaves your account: item + shipping + the <b>Buy tax</b> box (Massachusetts sales tax, 6.25%). A $58 copy with free shipping is $61.62 all-in and <b>passes</b>; $59 does not. In words: about 24% of every sale is gone before any profit, so a hit has to be roughly 31% under the Sell price at a 10% margin, 34% at 15%. That is why hits are rare and why the margin defaults to 10% now: with deal flow rather than cash as the limit, capital sitting idle at 15% earns nothing.</p>
<p><b>The resale certificate.</b> A Massachusetts vendor registration plus a resale certificate (Form ST-4) filed with eBay's tax-exemption program stops eBay charging sales tax on your purchases for resale. The day that approval lands, set the Buy tax box to 0: the all-in cost of every listing drops 6.25%, breakeven moves from about 24% to under 19% of the sale price, and the $61.63 Max buy above lets you pay $61.63 delivered instead of $58. Do not set it to 0 before the approval is real — the page would call listings hits that still cost you 6.25% more, and a 10% margin would quietly become 3.75%. The box is remembered in this browser and changes nothing in the collector, whose hourly log keeps counting at 6.25% until it is told otherwise.</p>
<p>Three details. Each listing is judged against the book <i>without itself</i>: you buy it, it leaves the market, and your relist competes with what remains — before this fix a cheap listing became its own card's cheapest copy and had to be 30% cheaper than itself. A Lightly Played listing is judged at the LP-discounted sell price. And a listing under <b>45% of A</b> gets a "review" badge instead of a verdict: at that price it is more often misidentified, damaged or fake than a bargain, so you spend thirty seconds on the photos and the seller before anything else.</p>

<h3>3. The Confidence, Window, Margin and Buy tax boxes</h3>
<p><b>Only show hits</b> filters the Raw Data tab to PASS rows. <b>Confidence</b> and <b>Window</b> together set the sales rate a card needs to count as liquid (the eBay Catalog README works it through); they move nothing else. <b>Margin</b> is the profit required on all-in cost; it moves Max buy and the PASS threshold and nothing else. <b>Net $</b> on the Catalog is what you clear at the Sell price; <b>Profit $</b> and <b>ROI %</b> on the Raw Data tab apply that to each listing's all-in cost, so sorting Raw Data by ROI shows the best buys first. The boxes are remembered in this browser and change nothing in the collector.</p>
<p><b>LP correction</b> beside them is read-only: how much less a Lightly Played copy sells for, by price tier. A listing that says LP is judged at the lower price. <b>Calibration</b> applies the measured shift to the sell price once enough outcomes exist. None of these boxes reach your phone: alerts follow the Notification Settings tab.</p>

<h3>4. What to do with the numbers</h3>
<ul>
<li><b>Buy</b> when the verdict says PASS — then read the title, the photos and the seller, and open the card's <b>Book</b> to see the copies you would compete with (greyed rows are the ones the floor ignored, and why).</li>
<li><b>List</b> at Sell, free shipping, Best Offer on with auto-accept about 3% under it. Unsold at 36–48 hours, cut to 0.90 × A or accept offers there. After another window it was mispriced or the card slowed — take the small loss and note why.</li>
<li>Treat "review" rows as a short daily to-do, not as hits. The same goes for the <b>Too cheap only</b> list (section 5): mostly wrong matches, occasionally a real steal.</li>
</ul>

<h3>5. Is it the right card? — the identity checks</h3>
<p>Every number above assumes a listing really is the card it was filed under. A wrong match hurts twice: it can look like a bargain (a reverse holo, a jumbo, a Japanese copy or a reprint filed under the expensive card), and it drags that card's prices. Four things guard against it.</p>
<ul>
<li><b>The title match</b> goes by card number first, then the set — by its words in the title or its printed total ("/165", from the open Pokémon TCG set list) — then the card's name, which has to agree, then the printing. When two sets hold the same number and name, the printed total decides: a Charizard titled "4/130 Base" is Base Set 2 (130 cards), not Base Set (102). A title that names a printing the catalog does not list for that card (reverse, 1st edition, jumbo, Master Ball…) is left unmatched rather than filed under the plain card. The catalog product a seller picked on eBay is used only when the title agrees with it.</li>
<li><b>Price against PriceCharting</b> — the one place a PriceCharting price is used on the eBay tabs. A listing under <b>40%</b> or over <b>300%</b> of the card's PriceCharting ungraded price is marked <b>mismatch</b>: it can never be a hit, and it is left out of the book, the sold prices, λ and the trends. Example: a $40 listing filed under a $120 card is at 33% → mismatch ↓; $420 is at 350% → mismatch ↑; $70 (58%) is judged normally. The rule is skipped when PriceCharting has fewer than 20 sales a year behind its price, when the set is under 30 days old (new-set prices fall faster than PriceCharting follows), and on the cheap side for MP/HP copies. Tick <b>Too cheap only</b> on Raw Data to go through the cheap ones by hand.</li>
<li><b>Item specifics.</b> A listing that clears the price gate is looked up once, and what the seller entered — card number, card name, set, language, card size, finish — is compared with the matched card. <b>PASS ✓</b>: they agree. <b>PASS ID?</b>: not read yet, or the seller left them blank, so the match rests on the title. <b>ID conflict</b>: they describe another card; hover the badge for what disagreed. A wrong printed total alone ("155/168" on a /128 set) is noted, not treated as a conflict, when the number, name and set agree.</li>
<li><b>Anniversary reprints.</b> The Celebrations sets reprint famous old cards with their original number: the 30th Celebration Charizard still says 4/102, like the 1999 Base Set card it copies, with an anniversary stamp added. Sellers label the copy "Base Set", so the title and the item specifics both point at the original. For a card that has such a reprint, a listing priced nearer the reprint than the card itself gets the verdict <b>reprint?</b> and cannot be a hit, and every alert on that card - auctions too, where the price says nothing until the end - carries a "Reprint check" box with the reprint's picture. Example: Base Set Charizard at $446, its reprint at $199.50; a listing under about $298 is nearer the reprint.</li>
<li><b>Your eyes.</b> None of this reads the photos. Before any buy: front and back, the number in the corner, the language, the stamp.</li>
</ul>
<p>The four numbers of the price rule are constants at the top of the collector (PC_LOW, PC_HIGH, PC_MIN_SALES, PC_NEW_SET_D). How often the matcher is right has not been measured yet: sort Raw Data by <b>vs PC %</b> ascending, open the first 150 listings, and count how many are really the card in the first columns — that count is the first real accuracy number, and the misses show which rule to tighten.</p>

<h3>6. The scam screen</h3>
<p>Scam listings hurt twice: they show up as the best "deals", and while they are live they sit in the card's book as the cheapest copy and would drag the floor and Max buy down for everyone. eBay removes them eventually, but only after the damage. So every listing gets a score from cheap signals — how far under the card's price it is, a seller with fewer than 10 ratings, one photo, a stack of copies of a card that does not come in stacks, a long delivery window, with credit for Top Rated Plus and long-established sellers. No single one of those decides: an honest new seller at a fair price scores 3 and stays. A photo already used by another seller is the exception - it makes a listing suspect by itself. Score 5 or more is <b>suspect</b>: kept out of every statistic and hidden on Raw Data behind the Show suspects box (the Notification Settings tab has a switch to be alerted about them all the same, labelled). 3–4 is <b>watch</b>: in the statistics, badged, but never allowed to set the floor. Raw Data also leaves out any listing with fewer than 2 photos, because condition cannot be judged without the back — the Catalog still counts those listings, since buyers buy from them.</p>
<p>The score is calibrated from outcomes, like the price: every closed listing keeps the score it had, and the Scam screen button tabulates how each tier and each signal turned out — sold, ended, or "gone" (pulled before its end date, which is what eBay does to scams). A signal that fires mostly on listings that later vanish is earning its points; one that fires on listings that sold normally is catching honest sellers and gets cut. Thresholds are adjusted by hand from that table, not fitted automatically. First adjustment, October 6 (5,774 closed listings: clean 0.5% gone, watch 3.2%, suspect 11.5%): the points for a seller with 10–49 ratings, for a feedback percentage below the bar and for no returns were dropped - listings carrying them were pulled no more often than clean ones - and a borrowed photo (8 of 16 pulled, none sold) became suspect on its own.</p>

<h3>7. Leads and the offer list</h3>
<p>The gate only speaks for cards with 5 or more recorded eBay sales, and most listings are on cards that do not have them yet. Two tools widen the net; neither produces a "PASS".</p>
<ul>
<li><b>LEAD</b> (Raw Data verdict, "Leads only" filter). For a card eBay cannot judge yet, PriceCharting's ungraded price stands in for the anchor: Sell = the lower of 95% of that price and 50¢ under the cheapest other believable copy listed (93% of it when there is no other copy), then the same fees, margin and tax. The card must show at least 100 PriceCharting sales a year and a price of $40 or more. The cap by live copies is what matters: PriceCharting lags a falling price (30th Celebration Mew ex: $147 there while copies sat unsold at $95). A lead is a listing worth opening - vintage leads especially are often cheap because of condition.</li>
<li><b>Offer list</b> (button above the Raw Data table). Every open listing that takes Best Offer where an accepted offer at that listing's Max buy is at most 30% under the asking price, smallest ask first. It is built from each card's cheapest copies, so it reaches listings of any age - and the ones that have sat are the likeliest to accept. You send the offers on eBay yourself; an accepted offer is binding, so look at the photos first.</li>
</ul>

<h3>8. Auctions sent to my phone</h3>
<p>The chip <b>Auctions sent to my phone</b> swaps the table over: every ordinary listing disappears and you see only the auctions the collector pinged you about, kept for 60 days. "Listed within" becomes "Alerted within".</p>
<ul>
<li><b>Bid at alert</b> is the bid when your phone buzzed; <b>Sold for</b> is what the auction closed at.</li>
<li><b>Max buy, Profit and ROI</b> are the worst case if you win: you pay your whole Max buy, so ROI is your margin.</li>
<li><b>Profit at final</b> and <b>ROI at final</b> are the best case: the price it closed at with no bid from you. Your own bid would have pushed that price up, or lost to a higher hidden maximum.</li>
<li><b>Verdict</b> says how it closed against your Max buy: PASS, over max buy, no bids, not finished, or no result.</li>
</ul>
<p>In this view the numbers follow the margin and buy tax saved on the Notification Settings tab, not the boxes above, which are greyed out.</p>

<h3>9. Where hits come from — and the real cash cycle</h3>
<p>Two facts shape expectations. First, the fee wedge: a hit is a 31%-off listing on a card that sells daily, and other scanners watch the same new-listing feed, so genuine ones are rare and go in minutes. Second, "sell within 48 hours" is not a 48-hour cash cycle: inbound shipping (3–5 days), the sale, outbound delivery (2–5 days) and eBay's payout hold (1–3 days) make it <b>8–14 days</b>, so a dollar turns two or three times a month, not fifteen. Realistic early output, if the guesses hold: a few buys a day across all channels at $7–12 each on $100 cards.</p>
<p>The steadier sources of 30%-off buys are the ones a new-listing scanner never sees: Best Offers on listings that have sat ten days or more, auctions ending at odd hours, and price drops on old listings (a relist or a cut never appears as "new"). The planned next step is a daily offer list — the site computes the price to offer on aged listings of liquid cards and you click through on eBay, since eBay's API will not send offers — built once the deal-speed table says what new listings deliver on their own. Two housekeeping items are worth real money: verify your actual label cost (two dollars moves breakeven two points), and look into a Massachusetts resale certificate filed with eBay, which removes the 6.25% buying tax and moves breakeven from 24% to under 19% of the sale price — confirm the obligations with the state before relying on it.</p>
`,
al: `
<h3>1. What this tab does</h3>
<p>These settings decide which listings are sent to your phone. They live on the collector, the machine that watches eBay around the clock, so they keep working with this page closed. They are separate from the boxes on the eBay Raw Data tab, which only change what the tables show.</p>

<h3>2. What counts as a hit</h3>
<p><b>Margin</b> is the return you require on everything you pay; it sets Max buy for every listing. <b>Buy tax</b> is the sales tax added when you buy (6.25% in Massachusetts; set it to 0 only once eBay has your resale certificate). <b>Confidence</b> and <b>Sell window</b> together decide how fast a card has to be selling before it can alert: 70% in 48 hours needs about 0.6 sales a day. A listing that clears all of it on a card with 5 or more recorded eBay sales is a <b>hit</b>.</p>

<h3>3. Only alert when</h3>
<p><b>Profit is at least</b> is a floor in dollars on top of the percentage, so a $3 profit does not buzz your phone. <b>Buy price between</b> caps what one alert can ask you to spend. The collector itself reads listings from $25 to $500.</p>

<h3>4. What to send</h3>
<ul>
<li><b>Hits</b> - loud alerts for listings that pass.</li>
<li><b>Leads</b> - listings on cards eBay has too few sales to judge, priced from PriceCharting instead. Many more of them, quieter, and each needs a careful look.</li>
<li><b>Scam-watch listings</b> - some warning signs (score 3 or 4). The alert lists each one with its points.</li>
<li><b>Suspect listings</b> - score 5 or more. Off unless you switch it on; then they arrive titled SUSPECT with every reason. A listing whose photo is also used by another seller never alerts.</li>
<li><b>Auctions</b> - an auction ending in 9 to 15 minutes whose bid is still under your Max buy, with the most you may bid.</li>
</ul>
<p>A listing whose price drops into range during its first 2 days alerts as a <b>price drop</b>.</p>

<h3>5. Quiet hours</h3>
<p>Between the two hours an alert still lands in the ntfy app, but without sound. Nothing is held back.</p>

<h3>6. Saving</h3>
<p><b>Save alert settings</b> sends the numbers to the collector over a private, signed channel; only this site, unlocked with your password, can do it. The box on the right, <b>On the collector now</b>, shows what the machine reports is in force. A save usually shows up there within a minute or two. <b>Send test alert</b> checks the path to your phone.</p>

<h3>7. Preview, History and Wrong matches</h3>
<p><b>Preview</b> runs the last 24 hours of listings through the numbers on the left, saved or not, so you can see what a change would have sent. <b>History</b> lists the last 40 alerts with what you answered on the phone and what became of each listing. <b>Wrong matches</b> keeps, for a year, every clean listing you answered "No, not the same card" to - the cases to tighten the title matcher against.</p>

<h3>8. The alert on your phone</h3>
<p>Tapping an alert opens a check screen with two questions. <b>First: is it the same card?</b> PriceCharting's picture on the left, the eBay photos on the right (tap the eBay photo to open the listing), and under them the set and card number, the price, and the sales on each side. The total price is the card plus shipping plus buy tax, at the tax saved here when the alert went out. <b>Second: what condition is it?</b> Near Mint and Lightly Played each show the Max buy, the profit and the ROI; choosing one opens the listing on eBay. "Next question" only looks ahead and records nothing. An alert already on your phone keeps the numbers it was sent with.</p>
`,
rv: `
<h3>1. What this tab is</h3>
<p>Your own flips: what you bought on eBay, what you sold, and what each one made. The collector reads your eBay account every half hour, with the approval you gave on October 5. It only reads; it never buys, bids, lists or changes anything. eBay hands back the last 90 days, so the record builds up from the day the account was linked. The approval lasts about 18 months; after that the link step has to be run again.</p>

<h3>2. How a purchase is paired with its sale</h3>
<p>eBay does not connect a card you bought to the listing you later sold it under. The pairing is exact when your sale listing's <b>Custom label (SKU)</b> holds the item number of the listing you bought. Otherwise the two are matched by card - the same title matcher the rest of the site uses - oldest purchase first. A purchase with no sale yet shows as <b>holding</b>. A sale with no purchase on record (a card from your own collection, say) is listed without a net, because there is no cost to take off.</p>

<h3>3. The numbers</h3>
<ul>
<li><b>Paid</b> - card price plus shipping plus sales tax.</li>
<li><b>Listed before buy</b> - how long the listing had been up when you bought it, in hours.</li>
<li><b>Sale total</b> - what your buyer paid you, before eBay's fee. <b>Hours to sell</b> - how long your own listing was up.</li>
<li><b>Hours held</b> - from paying to being paid: how long the money was tied up.</li>
<li><b>eBay fees</b> - the fee eBay actually charged, not an estimate.</li>
<li><b>Ship + supplies</b> - still an estimate ($4.50 label + $0.30 supplies); your real label cost is not read yet.</li>
<li><b>Net</b> = Sale total - eBay fees - ship and supplies - Paid. <b>ROI</b> = Net / Paid.</li>
<li><b>Source</b> - which alert led to the purchase (hit, lead, price drop, auction), or "other". <b>Predicted net</b> is what that alert promised; the gap to Net shows how far the tool's estimate was off.</li>
</ul>

<h3>4. The period and the totals</h3>
<p>Pick a year, then a range of months, or one month and a range of days. A card counts in the period it was <b>sold</b> in. The line above the table adds up the net for the cards in view, what was spent on them and the return, and shows the <b>cash tied up</b> in cards bought and not yet sold.</p>

<h3>5. What it does not handle yet</h3>
<p>Refunds and returns are not taken off. Real shipping label costs are not read. Purchases made more than 90 days before the account was linked are not on record.</p>
`
};
const README_TITLE = {pc: 'PriceCharting Catalog', ec: 'eBay Catalog', er: 'eBay Raw Data', al: 'Notification Settings', rv: 'Transaction Report'};

/* ---------------- Column help ---------------- */
const pct = v => (v * 100).toFixed(2).replace(/\.?0+$/, '') + '%';
const HELP = {
  card: {t: 'Card', f: 'PriceCharting product name = card name + [variant] + #number', m: 'Each printing is its own row with its own prices: a plain card, its [Reverse Holo], [Holo], [1st Edition] or [Shadowless] version are different products. The name links to the PriceCharting page.', e: '"Spinarak #6" and "Spinarak [Ditto] #6" are the same card number in the same set, at $0.83 and $15.24 — a seller who lists only "Spinarak 6/78" may not know which one they have.'},
  set: {t: 'Set', f: 'PriceCharting console-name', m: 'The set the card was printed in, in PriceCharting\'s naming. The table and the set dropdown are ordered by each set\'s release date.', e: '"Pokemon Base Set" (1999) sorts before "Pokemon Jungle" (1999-06) before "Pokemon Evolving Skies" (2021).'},
  num: {t: 'Set / Card', f: 'card number / printed set size, as the card itself shows it (36/123 = card 36 of a 123-card set)', m: 'The number after the slash is the set\'s printed size, taken from the open Pokemon TCG dataset and matched to PriceCharting\'s set names when the site is built each morning; a set that did not match uses the size the collector learns from eBay titles (most say "36/123") once it has seen it five times, and shows the bare number until then. Prefixed numbers (TG05, SV001, GG05) are shown as printed. Set + number + printing identify a card: a reverse holo, 1st Edition or shadowless printing shares the number and is its own row, tagged in the Card column. Secret rares run past the printed size (199/165).', e: 'Charizard ex 199/165: card 199 of Obsidian Flames, whose printed size is 165. Base Set 4/102 is Charizard; Jungle 4/64 is Kangaskhan.'},
  released: {t: 'Released', f: 'PriceCharting release-date', m: 'The card\'s original release date. Cards without one show "—" and their set is ordered by the earliest dated card in it.', e: '1999-01-09 for Base Set; 2022-07-01 for Pokémon Go.'},
  sales: {t: 'Sales/yr', f: 'PriceCharting sales-volume = units sold in the trailing 12 months, ALL grades combined', m: 'A liquidity measure — but it counts raw and graded sales together. For cheap modern cards almost nothing is graded, so it ≈ raw sales. For vintage cards graded sales can be most of it, so it overstates how often a raw copy sells. Use the Trend popup\'s "raw sale every N days" for the raw-only view.', e: 'Ivysaur #2 (1998 KFC): 45/yr in this column, but PriceCharting\'s page shows ungraded ≈ 12/yr, Grade 8 ≈ 12, PSA 10 ≈ 12, Grade 7 = 6, Grade 9 = 3. 12+6+12+3+12 ≈ 45.'},
  ungraded: {t: 'Ungraded $', f: 'PriceCharting loose-price', m: 'The market price of an ungraded copy — a trailing average of recent raw sales (mostly eBay). This is the anchor: every other number is measured against it. It only moves when new raw sales land, so a slow card\'s price can sit unchanged for weeks. It blends all conditions; a near-mint copy sells closer to the Grade 7–8 price.', e: 'If the anchor is $42.00 and a listing is $27.99 + $4 shipping, the listing is 76% of anchor before tax — then fees, shipping out and drift decide whether that is a deal (see Trend popup).'},
  d7: {t: 'Δ7d %', f: '(P_today − P_7_days_ago) / P_7_days_ago × 100', m: '"Did something just happen." On a slow card this is usually one sale landing, so pair it with a Sales/yr floor before trusting it. Sort descending for cards that just jumped (sell candidates), ascending for cards that just dropped.', e: '$42.00 today, $42.50 a week ago → (42.00 − 42.50) / 42.50 = −1.2%.'},
  d30: {t: 'Δ30d %', f: '(P_today − P_30_days_ago) / P_30_days_ago × 100', m: 'The core trend number and the one to sort by. Read it with Δ7d and the slope: 30d down but 7d flat and the slope flattening is a card that may be settling; all of them down is a card still falling. A drop is either mispricing (opportunity) or news (a reprint, a rotation) — the number cannot tell which.', e: '$42.00 today, $48.00 thirty days ago → (42.00 − 48.00) / 48.00 = −12.5%.'},
  pos: {t: 'Range 90d %', f: '(P_today − Low_90d) / (High_90d − Low_90d) × 100', m: 'Where today\'s price sits between its 90-day low (0%) and high (100%). Two cards can both be −12% over 30 days: one falling back from a spike (still at 85% of its range) and one making new lows (5%). Different bets. Ignore it when the range is tiny, and remember a low position during a steady decline is a falling knife — it is only a signal once the 30-day trend has flattened. Needs 60 days of history.', e: 'Low $38.00, high $52.00, today $42.00 → (42 − 38) / (52 − 38) = 4 / 14 = 29%.'},
  vd: {t: 'Volume drift 30d', f: 'Sales/yr_today − Sales/yr_30_days_ago   (and as % of the earlier value)', m: 'Because Sales/yr is a trailing 365-day count, the 30-day difference equals (sales in the last 30 days) minus (sales in the 30-day window that just fell out of the year — roughly the same month a year ago). So a positive number means this month beat the same month last year: a year-over-year demand signal that is automatically seasonally matched. It counts all grades, so on vintage cards it is mostly a graded-market signal, and small counts are noise — +2 on a base of 40 means nothing. Sorting and the range filter use the percent. Rising volume with a rising price is real heat; rising volume with a falling price is a supply flood (a reprint hitting the market), the pattern where a "bargain" keeps getting cheaper.', e: '210 today, 196 thirty days ago → +14 sales, +14 / 196 = +7.1%.'},
  vol: {t: 'Volatility %', f: 'median of |ln(P_t / P_t−1)| over the days the price moved in the last 90 days', m: 'The typical size of a move when the price moves. The median ignores a single wild day, which a standard deviation would not. It sizes the safety cushion in the buy gate: a card that moves 2% at a time can be bought at a thinner discount than one that moves 12%. Needs at least 3 moves.', e: 'Moves of 3.82%, 3.75%, 1.78%, 4.98%, 1.40%, 1.18% → sorted 1.18, 1.40, 1.78, 3.75, 3.82, 4.98 → median = (1.78 + 3.75) / 2 = 2.77%.'},
  ts: {t: 'Slope 30d %/mo (Theil–Sen)', f: 'median over every pair of days (i, j) in the last 30 days of (ln P_j − ln P_i) / (j − i), then converted to % per month: (e^(slope × 30) − 1) × 100', m: 'The robust trend: the median of all pairwise slopes, so one spike day barely moves it, unlike a fitted line. It is the drift used in the buy gate (only negative drift counts against the sell price). Δ30d uses two endpoints; this uses all 465 pairs, so it is the steadier version of the same idea. Needs 10 points in the window.', e: '31 daily prices sliding from $48 to $42 → median pairwise slope −0.00413 per day → e^(−0.00413 × 30) − 1 = −11.7% per month. A plain regression gave −0.44%/day here; add one spike day and the two diverge.'},
  ec_price: {t: 'Price $ (eBay)', f: 'the anchor A once the card has any trimmed sales; until then the cheapest comparable listing', m: 'The card\'s market price from eBay alone, used by the $50–$150 default filter and the scam screen\'s price ratios. See Anchor $ for how it is built.', e: 'A = $94 → $94.'},
  ec_k: {t: 'Sold 30d (k)', f: 'count of comparable raw listings that sold in the last 30 days', m: 'The raw evidence behind λ. "Comparable" = ungraded, condition NM/LP or not stated, seller ≥ 98%. Sales only exist for listings the collector saw while they were live, so this starts at zero and grows.', e: '13 sales counted → k = 13.'},
  ec_d: {t: 'Days observed (D)', f: 'days since the first listing of this card was seen, capped at 30', m: 'The denominator for rates. A card first seen 5 days ago with 2 sales is 0.4/day, not 2/30.', e: 'First seen 19 days ago → D = 19.'},
  ec_lam: {t: 'λ — raw sales per day', f: '25th percentile of Gamma(k + ½, D)   (posterior for a Poisson rate with a flat prior)', m: 'Expected raw buyers per day, stated conservatively: the value the true rate exceeds three times out of four. With few sales it reads well below k/D on purpose; after ~20 sales it converges. It decides whether a card is liquid at your Confidence and Window, how long a credible copy may sit before it is ignored (1.6 ÷ λ days), and the Exp. days column.', e: 'k = 12, D = 18: k/D = 0.67/day, but λ = 0.56/day. k = 2, D = 10: k/D = 0.20 but λ = 0.11.'},
  ec_n: {t: 'Active (N)', f: 'number of comparable raw listings currently open for this card', m: 'The size of the book you would be competing in. Only comparable copies count (see Sold 30d).', e: '4 open NM/LP copies from ≥98% sellers → N = 4.'},
  ec_p: {t: 'p₁ p₂ p₃ — the book', f: 'the three cheapest comparable listings by total price (item + shipping); Best Offer copies ranked at 90% of ask', m: 'The three cheapest open copies as they are, before the credibility rules. A Best Offer listing at $122 is shown as $109.80 because that is roughly what it will actually take. The Floor column is the cheapest of these that is allowed to set the price; the Book popup greys the ones that are not.', e: 'Open copies $122 (BO), $123, $129 → p₁ = 109.80, p₂ = 123, p₃ = 129.'},
  ec_mu: {t: 'New/day (μ)', f: 'comparable listings first seen in the last 30 days ÷ D', m: 'The supply arrival rate — the counterpart of λ. Read it against λ in the In/out column.', e: '20 new comparable listings over 19 days → μ = 1.05/day.'},
  ec_dos: {t: 'Days of supply', f: 'N ÷ λ', m: 'How long the current book would take to clear at the observed demand. Under 7 = tight market, undercuts rare, price at pₙ − $1. Over 30 = glutted; sellers get impatient and the floor erodes — undercut by ~3% and do not count on rank 2.', e: 'N = 4, λ = 0.57 → 7.0 days.'},
  ec_io: {t: 'In/out (μ ÷ λ)', f: 'new listings per day ÷ sales per day', m: 'Above ~1.2 supply is piling up and the floor will be lower next week — your buy needs a bigger discount or a pass. Below ~0.8 supply is draining and prices firm. It is the eBay, raw-only version of PriceCharting\'s volume drift.', e: 'μ = 1.05, λ = 0.57 → 1.84: listings are arriving almost twice as fast as they sell.'},
  ec_smed: {t: 'Sold median $', f: 'median total (item + shipping) of the last 10 comparable raw sales', m: 'What buyers have been paying, as a plain median of the last ten. The anchor A does the same job more carefully (trimmed, recency-weighted); this stays as a quick reference and for the hot-card realized check. Best Offer sales are recorded at the listed price, so they may overstate by ~10%.', e: 'Same ten sales as above → $99.50.'},
  ec_s80: {t: 'Sold 80th percentile $', f: '80th percentile of the last 10 comparable sale totals', m: 'The top of the realistic range: only one sale in five went higher. Shown for reference; the Sell price is anchored on A, not on this.', e: 'Ten sales 92 … 110 → 80th percentile ≈ $104.'},
  ec_hrs: {t: 'Hours to sale', f: 'median hours from listing to sale over the last 10 comparable sales', m: 'How fast copies actually move. Under 48 h is one of the five hot-card checks. Resolution is the tracker\'s cadence (about an hour for fast sales).', e: 'Sale times 4, 9, 15, 22, 30, 41, 55 h → median 22 h.'},
  ec_st: {t: 'Sell-through %', f: 'of comparable listings first seen 3–33 days ago, the share that sold within 48 hours of going up', m: 'Listings are followed for their first 2 days only, so this is the share that sold inside your window. Once measured, a card needs at least 25% to count as liquid (the weakest card that passed the old bar, 50% within 7 days, stood at 25%); ≥ 35% is a hot-card check. Most listings are priced above what sells quickly, so even a fast card sits well under 100%. Needs at least 3 such listings.', e: '4 of 14 eligible listings sold within 2 days → 29%.'},
  ec_A: {t: 'Anchor A — what buyers pay', f: 'recency-weighted robust centre of the card\'s comparable sales in the last 30 days (60 if fewer than 5), after trimming outliers: weighted median under 8 sales, Hodges–Lehmann from 8', m: 'The card\'s price from what actually sold, with Lightly Played sales lifted to NM-equivalent, a 10-day half-life so last week counts more than three weeks ago, and two trims (Tukey fences, and a quarter-to-four-times-the-median band) that drop a Best Offer sale recorded at its ask or a copy that was really a different printing. Shows "thin" and the gate stays shut until a card has 5 sales behind it; hover for the count.', e: 'Sales 88, 90, 92, 94, 95, 96, 98, 99, 102, 105, 150 (BO at ask), 42 (wrong printing) → 150 and 42 trimmed → A = $94.'},
  ec_L: {t: 'Floor L — the cheapest credible copy', f: 'cheapest open comparable copy by effective price (Best Offer at 90%, LP lifted to NM-equivalent) that is not: watch/suspect tier, from a seller under 50 ratings or under the feedback bar, under 75% of A, or sat longer than 1.6 ÷ λ days (1–7)', m: 'The copy you must actually beat. A copy far under A is a deal or junk, not a price; a thin seller\'s copy is shown but never sets the price; a copy that has sat longer than this card\'s buyers allow has been passed over. The Book popup greys the copies the floor ignored.', e: 'Book $40, $70 (9 days old), $85 (3-feedback seller), $96 (Best Offer), $99 → floor = 96 × 0.9 = $86.40.'},
  ec_S: {t: 'Sell $ — the list price', f: 'min(L − $0.50, 0.95 × A), rounded down to .99; 0.93 × A with no credible floor; capped by the median of fast sales when the card has 8+ sales that sold within 48 h of listing', m: 'What you type into the listing, with free shipping. Just under the credible competition, never more than 5% under what buyers pay. Unsold at 36–48 h, cut to 0.90 × A. On the Raw Data tab this is computed per listing with that listing left out of the floor, because once you buy it, it is no longer competition.', e: 'L = $86.40, A = $94 → min(85.90, 89.30) = 85.90 → $84.99.'},
  ec_prob: {t: 'P(sale in window) %', f: '1 − e^(−λ × T), T = the Window box in days (rank 1)', m: 'The chance at least one buyer arrives inside your window while you are the cheapest credible copy. A card is liquid when this clears your Confidence; equivalently λ ≥ −ln(1 − Confidence) ÷ T.', e: 'λ = 0.99, 48 h → 1 − e^(−1.98) = 86%. λ = 0.56 → 67%, under a 70% bar: not liquid.'},
  ec_edays: {t: 'Expected days (at Confidence)', f: '−ln(1 − Confidence) ÷ λ', m: 'Days at the credible floor until a sale is as likely as your Confidence. The honest window for a card that is not liquid at your settings. Judge flips by profit per day, and this is the denominator.', e: 'λ = 0.56, 70% → 1.2 ÷ 0.56 = 2.1 days. λ = 0.1 → 12 days: not a flip card.'},
  ec_maxbuy: {t: 'Max buy $ (all-in)', f: 'net = Sell × (1 − 0.1325 × 1.065) − $0.40 − $4.50 − $0.30 = 0.8589 × Sell − $5.20;   max buy = net ÷ (1 + Margin)', m: 'The most you can pay in total — item + shipping + your sales tax — and still clear your Margin after eBay\'s fee (charged on the buyer\'s total including their tax), the per-order fee, the tracked label and supplies. Greyed "illiquid" when the card does not clear the liquidity rule; nothing on such a card can pass. A listing PASSes when its all-in is at or below this.', e: 'Sell $84.99 → net = 0.8589 × 84.99 − 5.20 = $67.80 → max buy = 67.80 ÷ 1.10 = $61.63: a $58 copy with free shipping ($61.62 with tax) passes.'},
  ec_net: {t: 'Net $ — proceeds at the sell price', f: '0.8589 × Sell − $5.20', m: 'What lands in your account if the card sells at Sell: the buyer total minus eBay\'s fee (on the total including the buyer\'s tax), the $0.40 per-order fee, the $4.50 tracked label and $0.30 of supplies. Depends on the anchors, not on Margin — Margin only decides how much of this you may spend on the buy.', e: 'Sell $84.99 → $67.80.'},
  ec_hot: {t: 'Hot', f: 'all five checks pass: k ≥ 5 · 48-hour sell-through ≥ 35% · median hours to sale ≤ 48 · sold median ≥ 95% of the median ask · last 5 sales ≥ 97% of the 5 before', m: '"Candidate" means the history says demand outruns supply. "Confirmed" (✓) means the next three copies listed after the flag all sold within 48 hours — a test on data the checks never saw. A copy that sits more than 48 h resets the count. "fails n" tells you how many checks a card with enough sales is missing; hover for which.', e: 'A card with 13 sales, 40% sell-through, 22 h median, prices realized at ask and a flat trend is a candidate; three quick sales later it is confirmed.'},
  ec_book: {t: 'Book', f: 'the live data behind this card\'s row', m: 'Opens the competing listings (ranked, with links) and the recent sales with their time to sale. This is what to look at before every buy: whether the floor is a credible copy, whether the sales were Best Offer (recorded at ask, so possibly lower), and what condition sold.', e: ''},
  et_spm: {t: 'Sales/month (eBay)', f: 'raw sales recorded in the last 30 days, from the daily rollup', m: 'The eBay counterpart of PriceCharting\'s sales/yr, but raw-only and monthly. Today it equals Sold 30d; it lives in the Trends band because it is the series the Volume drift and the Trend chart are built on.', e: '13 sales in the last 30 days → 13.'},
  et_d7: {t: 'Δ7d % (eBay)', f: '(P_now ÷ P_7 days ago − 1) × 100, where P = trailing 7-day median of raw sale totals', m: 'The eBay price line is the median of what raw copies actually sold for in the last 7 days (needs 3 sales in the window, else blank). This is its one-week change. On thin cards it moves because different copies sold, not because the market moved — trust it on cards with dozens of sales.', e: 'P today $87.62, P a week ago $88.30 → −0.8%.'},
  et_d30: {t: 'Δ30d % (eBay)', f: '(P_now ÷ P_30 days ago − 1) × 100', m: 'One-month change of the 7-day median sale price. Needs 30 days of eBay history.', e: '$87.62 vs $91.00 → −3.7%.'},
  et_pos: {t: 'Range 90d % (eBay)', f: '(P_now − Low90) ÷ (High90 − Low90) × 100 over the 7-day median series', m: '0% = at the 90-day low of realized raw prices, 100% = at the high. Needs 60 days of history and 10 valid points.', e: 'Low $85.72, high $100.17, now $87.62 → 13%.'},
  et_vd: {t: 'Volume drift 30d (eBay)', f: 'sales in the last 30 days − sales in the 30 days before, and the % change', m: 'Month-over-month demand. PriceCharting\'s version compares against the same month a year earlier (seasonal); eBay history starts now, so this is month-over-month until a year has passed. Rising sales with a falling price = supply flood; rising sales with a rising price = real demand. Needs 60 days.', e: '55 sales vs 48 the month before → +7 (+14.6%).'},
  et_vol: {t: 'Volatility % (eBay)', f: 'median |ln(P_t ÷ P_t−1)| over days in the last 90 where the 7-day median changed; needs 3 changes', m: 'The typical day-to-day move of the realized price. Includes sampling noise on thin cards (which three copies sold), so it reads higher than PriceCharting\'s.', e: 'Daily moves of 0.3%, 0.4%, 0.5%, 1.1% → median 0.45%.'},
  et_ts: {t: 'Slope 30d %/mo (eBay)', f: 'Theil–Sen median of pairwise slopes of ln P over the last 30 days, shown as (e^(slope × 30) − 1) × 100', m: 'The robust trend of realized raw prices: the middle of all pairwise slopes, so one odd sale does not move it. Needs 30 days and 10 valid points. Negative = drifting down.', e: 'Median pairwise slope −0.00178/day → (e^(−0.0534) − 1) × 100 = −5.2%/mo.'},
  et_trend: {t: 'Trend (eBay)', f: 'the daily rollup behind the Trends band', m: 'Opens the chart: bars are raw sales per day, the blue line the 7-day median sale price, the green line the cheapest comparable ask that day, dashed lines the 90-day high/low and the Sell price. Same controls as the PriceCharting chart. The stats strip below it shows the trend columns and the pricing numbers side by side.', e: ''},
  er_listed: {t: 'Listed within (h)', f: 'hours since the listing was created on eBay', m: 'Deals on liquid cards are gone in minutes to hours, so the freshest rows matter most. The filter takes one number: type 2 to see only listings posted in the last 2 hours. The tab holds listings first seen in the last 24 hours; sold or ended ones stay visible with their status. The tab refreshes itself every minute while it is open, and rows that arrived since your last look are tinted green.', e: '0.3 = listed about 20 minutes ago.'},
  er_title: {t: 'eBay title', f: 'the seller\'s title, linked to the listing', m: 'What the parser matched to the catalog card in the first columns. Always read it before buying: variant words (reverse, 1st edition, shadowless), condition claims and anything odd. If the match looks wrong, that is a parser pattern to fix — the Unmatched button shows the ones it refused.', e: '"Charizard ex 199/165 Obsidian Flames SIR NM" → Charizard ex #199, Pokemon Obsidian Flames.'},
  er_item: {t: 'Item $ / Ship $', f: 'the listed price and the seller\'s shipping charge to your ZIP', m: 'Calculated shipping is estimated for the ZIP the collector was given. "free" means the seller folded shipping into the item.', e: '$118 + $4 shipping.'},
  er_total: {t: 'Total $', f: 'item + shipping', m: 'The buyer total, which is how everything else on the eBay tabs is measured (sold prices, the book, the Sell price).', e: '118 + 4 = $122.'},
  er_allin: {t: 'All-in $', f: 'item + shipping + item × Buy tax (the box above the table: 6.25% Massachusetts sales tax; 0 once eBay has approved your resale certificate)', m: 'What actually leaves your account. This is the number compared to Max buy. Set the Buy tax box to 0 only after the exemption is real: until then a listing the page calls PASS costs 6.25% more than it shows.', e: '118 + 4 + 7.38 = $129.38 at 6.25%; $122.00 at 0%.'},
  al_margin: {t: 'Margin (alerts)', f: 'Profit ÷ all-in cost must be at least this', m: 'The return you require on what you pay, after eBay\'s fee, shipping, supplies and buy tax. It sets Max buy for every listing, so a higher margin means fewer but fatter hits. This one decides your phone alerts; the Margin box on the eBay Raw Data tab only changes the tables.', e: '10% on a card that nets you $66 after costs: Max buy is $60, and a $60 all-in purchase leaves $6.'},
  al_tax: {t: 'Buy tax (alerts)', f: 'Sales tax added to the item price when you buy', m: 'Massachusetts adds 6.25% to what you pay on eBay. It counts against your profit. Set it to 0 only once eBay has your resale certificate on file; otherwise every profit shown will be too high by the tax.', e: '$70 card: 6.25% adds $4.38, so the all-in cost is $74.38.'},
  al_conf: {t: 'Confidence (alerts)', f: 'How sure the model must be that a buyer turns up inside your sell window', m: 'A card only counts as liquid, and so can only produce a hit, when a buyer is at least this likely to arrive within the sell window. Higher = only the fastest-selling cards, so fewer alerts. Lower = more cards, but some will sit longer.', e: '70% in 48 h needs about 0.6 sales a day; 80% needs about 0.8.'},
  al_win: {t: 'Sell window (alerts)', f: 'How long you are willing to wait for the resale', m: 'The time you give a card to sell after you list it. With Confidence it sets how fast a card has to be selling before it can alert. A longer window lets slower cards through.', e: '48 h is the default; 72 h admits cards that sell roughly every other day.'},
  al_minprofit: {t: 'Minimum profit', f: 'Net − all-in cost, in dollars', m: 'A floor in dollars on top of the percentage margin. A $30 card at 10% clears the margin with $3 of profit, which is not worth a trip to the post office; this stops those from buzzing your phone.', e: 'Set to 10: a hit with $5 profit is not sent, one with $16 is.'},
  al_price: {t: 'Buy price range', f: 'The listing\'s total (item + shipping) must fall between the two numbers', m: 'Caps how much a single alert can ask you to spend, and skips listings too cheap to matter. The collector itself reads listings from $25 to $500, so a range wider than that changes nothing.', e: '$40 to $200: a $260 hit is not sent.'},
  al_hits: {t: 'Hits', f: 'Verdict PASS', m: 'Listings on cards with enough recorded eBay sales (5 or more) that clear your margin with everything counted. These arrive as loud alerts. Turning this off silences them.', e: 'A $70 listing of a card that sells for about $112 and moves daily.'},
  al_leads: {t: 'Leads', f: 'Verdict LEAD', m: 'Listings on cards eBay has too few sales to judge, priced from PriceCharting instead and capped by the cheapest other copy on sale. There are many more of them than hits and most need a careful look, so they arrive without sound and are marked "lead". Off by default.', e: 'About 45 a day against about 1 hit.'},
  al_watch: {t: 'Scam-watch listings', f: 'Scam score 3 or 4', m: 'A "watch" listing has some warning signs (a new seller, a very low price, a single photo) but not enough to be thrown out. Included: you still get the alert, and the check screen lists each warning with its points. Left out: you never hear about them.', e: 'A $60 listing of a $110 card from a seller with 12 ratings.'},
  al_quiet: {t: 'Quiet hours', f: 'Alerts arrive silently between the two hours, in your local time (24-hour clock)', m: 'Nothing is held back: during quiet hours an alert still lands in the ntfy app, but without sound or vibration, so it does not wake you. Outside those hours hits are loud again. The window can run past midnight.', e: '23 to 7: silent from 11 PM until 7 AM.'},
  al_live: {t: 'On the collector now', f: 'What the always-on machine reports in its live file', m: 'The settings actually in force, as the collector itself reports them, with the time of the last change it accepted from this tab and how many alerts it has sent. If this box and the numbers on the left disagree, the left side has not been saved yet. A save usually shows up here within a minute or two.', e: '"Last change from this tab: Oct 5, 1:42 AM".'},
  al_preview: {t: 'Preview', f: 'The last 24 hours of listings, judged with the numbers on the left', m: 'A dry run before you save: every listing first seen in the last 24 hours is put through the gate with the numbers on the left, whether or not they are saved. It shows what your phone would have received, so you can tune without waiting a day. "Now" says whether that listing is still open.', e: 'Margin 10 → 1 listing; margin 5 → 4 listings.'},
  al_suspects: {t: 'Suspect listings', f: 'Scam score 5 or more, or a photo borrowed from another seller', m: 'Suspect listings are hidden from the tables and kept out of every statistic, and normally never alert. With this switch on, a suspect that would otherwise be a hit (or a lead, if leads are on) is sent to your phone with "SUSPECT" at the front of the title and each reason listed with its points; the check screen shows the same list in red, with how often eBay has pulled listings like it. So far that is about 1 in 9, against 1 in 200 for clean listings - and a scam eBay never catches shows up as "sold", so the real risk is higher. One kind never alerts even with the switch on: a listing whose photo is also used by another seller (half of those were pulled, none sold). If the photos look like stock images or the seller asks you to pay outside eBay, walk away.', e: '"SUSPECT: +$17 · Charizard ex #199 · $70" - "+3 seller feedback under 10, +2 priced 50-65% of the card\'s price = 5 points".'},
  al_wrong: {t: 'Wrong matches', f: 'Alerts you answered "No, not the same card" to, on listings the scam screen had not flagged', m: 'Every one is a case where the title matcher sent you a listing that was not the card it claimed. They are kept for a year, apart from the History list (which only holds the last 40 alerts), so the matcher can be checked and tightened against them. Two kinds end up here: titles the matcher read wrongly, which a rule can fix, and listings whose own title names one card while the photo shows another, which nothing but your eyes can catch. A No on a scam-watch or suspect listing is left out, because there it may mean "this is a scam" and not "this is another card".', e: 'eBay title "Charizard 11/108 Evolutions Holo Rare" - was matched to Charizard #11, Evolutions - the photo showed a Charizard VMAX.'},
  al_auctions: {t: 'Auctions', f: 'Auctions that end in 9 to 15 minutes with the current bid still under your Max buy', m: 'Every five minutes the collector looks at the auctions about to end. One on a card it can price, whose bid plus shipping and tax is still under what the gate would pay, is sent to your phone with the highest amount you may bid. Most bidding happens in the final seconds, so many of these will finish above your max: the alert gives you time to check the card, then you watch the listing and bid your max at the very end. eBay\'s automatic bidding never takes you over the amount you enter. Your profit and price filters apply to the max bid. The Preview on this tab does not include auctions. Every auction sent is kept for 60 days: on the Raw Data tab, switch on "Auctions sent to my phone" to see the bid at the ping beside what each one closed at.', e: '"Auction ends in 11 min · bid up to $46 · Team Rocket\'s Moltres ex #229".'},
  al_hist: {t: 'History', f: 'The last 40 alerts the collector sent', m: 'One row per alert: when it went out, the card and listing, the price and the profit it promised, whether it was a hit, a lead or a price drop, what you tapped on the phone\'s check screen (Yes near mint, Yes lightly played, or No), and what became of the listing. "Sold 40 min after the alert" tells you how long you really have. Your No answers are the running check on the matching: a string of them on one kind of card means the matcher needs a fix. An answer shows up a minute or two after you tap.', e: 'Oct 5, 12:40 AM · Charizard #11 · $45.81 · No · sold 3.2 h after the alert.'},
  er_aubid: {t: 'Bid at alert $', f: 'the highest bid at the moment your phone was pinged', m: 'Only in the auction view (the "Auctions sent to my phone" switch). It is the price on the screen 9 to 15 minutes before the end, before the last-second bidding, with the number of bids then. For the few alerts sent before October 6 it is worked back from the total the alert recorded.', e: '$41.00 with 6 bids.'},
  er_ausold: {t: 'Sold for $', f: 'the winning bid when the auction closed', m: 'Read from eBay a few minutes after the end. An auction that closed under 40% of the card\'s PriceCharting price shows "closed too cheap" in the Verdict and is not counted as a hit: other bidders do not let the real card go for that. "no bids" means it ended without a sale; a dash means the result is not in yet, or eBay no longer has the listing. This is the price with no bid from you in the auction.', e: '$58.00 with 14 bids.'},
  er_aupf: {t: 'Profit at final $', f: 'what selling the card brings in − (Sold for + shipping + buy tax)', m: 'The best case: what the flip would have made had you won at the price it actually closed at. Your own bid would have changed that price. If the winner\'s hidden maximum was above yours you would have lost; if it was below, you would have won but paid more than this, because eBay charges just enough to beat the next bidder. Set it beside Profit $, which in this view is the worst case - paying your whole Max buy. The truth, when you win, lies between the two. What the card sells for is the figure the alert used; margin and buy tax are your saved alert settings.', e: 'Sells for a net $70.00, closed at $58.00 + $4.00 shipping → $8.00.'},
  er_auroi: {t: 'ROI at final %', f: 'Profit at final ÷ (Sold for + shipping + buy tax)', m: 'The best-case return, at the price the auction closed at. ROI % beside it is the worst case and always equals the margin saved on the Notification Settings tab, because Max buy is set to return exactly that. Change the margin there and both Max buy and the verdict here are re-judged for every past auction.', e: '$8.00 on $62.00 = 12.9%.'},
  er_mm: {t: 'Mismatch', f: 'Your own verdict: this listing is not the card it was matched to', m: 'Tick it and the row turns light red and stays where it is. The listing leaves the statistics (the book, the sold prices, the sales rate, the trends), it can no longer be a hit, and it comes out of the "If you had bought every hit" total. Untick to undo. The matcher also learns from it: the same title from that same seller is never filed under that card again (another seller with the same words is not affected), that seller\'s other listings of the card are held back, and a word that turns up in three of your mismatches while being rare everywhere else becomes a warning word that holds listings back. A "No, not the same card" on your phone counts the same way, for a listing the scam screen had not flagged. What it cannot learn from is a listing whose title is right and whose photo is wrong: the words in it are all the right card\'s.', e: 'A "GOLD Classic Collection" listing filed under the plain card: tick it. After three like it, "gold" is held back on its own.'},
  er_pcsales: {t: 'PC sales', f: 'PriceCharting sales count for the last 12 months ÷ 12', m: 'How many copies of this card PriceCharting records as sold in an average month. It counts every grade together, raw and graded, so it runs high for cards that are mostly sold graded. Compare it with eBay sales: a card PriceCharting calls busy that this collector has barely seen sell is either graded-heavy or its sales are not being caught yet.', e: '3,000 sales in 12 months → 250.'},
  er_ebsales: {t: 'eBay sales', f: 'Raw copies this collector has recorded as sold in the last 30 days', m: 'Counted from the listings it tracks and has confirmed sold - raw singles only, $25 to $500. The collector has been running since September 28, so until late October this covers fewer than 30 days, and sales it has not confirmed yet are missing. It is the same number as "Sold 30d" on the eBay Catalog tab.', e: '12 = twelve raw copies recorded sold.'},
  period: {t: 'Period', f: 'A year, then a range of months (1 to 12), or a range of days inside one month', m: 'Choose "by month" and type the first and last month to add up, for example 1 to 12 for the whole year or 10 to 10 for October alone. Choose "by day" to pick one month and a range of its days, for example days 5 to 20. On the Transaction Report a card counts in the period it was SOLD in (a card not sold yet counts by its purchase date and adds nothing to the net). On Raw Data a hit counts by when its alert went out. Times are your computer\'s local time.', e: 'Year 2026, by day, in month 10, from 5 to 20.'},
  rv_status: {t: 'Status', f: 'sold · holding · sold, no purchase on record', m: '"sold": a purchase paired with its sale. "holding": bought and not sold yet (its cost counts in "cash tied up"). "sold, no purchase on record": you sold a card eBay shows no purchase for in the last 90 days, a card from your own collection for instance, so there is no cost to take off and no net. A purchase is paired with a sale exactly when the sale listing\'s Custom label (SKU) holds the purchase\'s eBay item number; otherwise by the same card, oldest purchase first.', e: 'Put 147608780027 in the Custom label when you relist that card.'},
  rv_bought: {t: 'Bought', f: 'When the purchase order was created', m: 'Date and time of your purchase, from your eBay account. The card name links to the listing you bought.', e: 'Oct 4, 9:23 PM.'},
  rv_paid: {t: 'Paid $', f: 'item price + shipping + sales tax', m: 'Everything the purchase cost you. When one order held several cards its shipping is split evenly between them.', e: '$30.00 + $6.00 + $2.25 = $38.25.'},
  rv_before: {t: 'Listed before buy (h)', f: 'purchase time − the listing\'s start time, in hours', m: 'How long the listing had been up when you bought it. From the collector\'s own record of the listing when it tracked it, otherwise looked up once on eBay; blank when eBay no longer has the listing.', e: '1.5 = you bought it an hour and a half after it was posted.'},
  rv_sold: {t: 'Sold', f: 'When your buyer\'s order was created', m: 'Date and time of the sale, linking to your listing.', e: 'Oct 6, 2:10 PM.'},
  rv_sale: {t: 'Sale total $', f: 'item price + shipping your buyer paid', m: 'What the buyer paid you, before eBay takes its fee. Sales tax the buyer paid is not included: eBay collects it and it never reaches you.', e: '$80.00 + $4.50 = $84.50.'},
  rv_tosell: {t: 'Hours to sell', f: 'sale time − your listing\'s start time', m: 'How long your own listing was up before it sold. This is the number to set against the Sell window you chose on the Notification Settings tab.', e: '36 = sold a day and a half after you listed it.'},
  rv_held: {t: 'Hours held', f: 'sale time − purchase time', m: 'How long your money was tied up in the card, from buying it to selling it. It includes the wait for the card to reach you and the time before you relisted it.', e: '96 = four days between paying and being paid.'},
  rv_fees: {t: 'eBay fees $', f: 'The marketplace fee eBay charged on the sale', m: 'The actual fee from your eBay account, not an estimate. When one order held several cards the fee is shared between them by value.', e: '$11.89 on an $84.50 sale.'},
  rv_out: {t: 'Ship + supplies $', f: 'Shipping label + supplies, the collector\'s standing estimate', m: 'For now this is the same estimate the buy gate uses ($4.50 label + $0.30 supplies), because the collector does not read your real label costs yet. If you ship some other way your true cost differs.', e: '$4.80.'},
  rv_net: {t: 'Net $', f: 'Sale total − eBay fees − ship and supplies − Paid', m: 'What the flip actually made. Blank until the card is sold, and blank for sales with no purchase on record.', e: '$84.50 − $11.89 − $4.80 − $38.25 = $29.56.'},
  rv_roi: {t: 'ROI %', f: 'Net ÷ Paid', m: 'The return on the money you put in. Compare it with the Margin you set on the Notification Settings tab: the gate promised at least that.', e: '$29.56 on $38.25 = 77.3%.'},
  rv_source: {t: 'Source', f: 'hit · lead · price drop · auction · other', m: 'Which alert, if any, led to the purchase: the collector looks for the listing you bought among the alerts it sent. "other" means it never alerted on that listing (you found it yourself, or bought it from the Offer list).', e: 'hit.'},
  rv_pred: {t: 'Predicted net $', f: 'The profit the alert promised when it went out', m: 'Set this beside Net: the gap is how far the tool\'s estimate was from what really happened. A run of flips where Net falls short of Predicted means the sell prices or the costs in the model need correcting.', e: 'Predicted $16.60, Net $13.70.'},
  er_pc: {t: 'PC ungraded $', f: 'PriceCharting loose-price of the card this listing was matched to', m: 'PriceCharting\'s price for an ungraded copy of the matched card — the same number as Ungraded $ on the PriceCharting tab. It is on this tab for one job: catching wrong matches (see vs PC %). Every pricing number on the eBay tabs — Anchor, Sell, Max buy, Profit — still comes from eBay sales alone.', e: 'A listing matched to Charizard ex #199 shows $120.00 here, whatever the listing itself asks.'},
  er_vspc: {t: 'vs PC %', f: '(Total ÷ PC ungraded − 1) × 100', m: 'How far the listing sits from PriceCharting\'s price for the matched card. Under 40% of that price (−60% or lower) the verdict is "mismatch ↓"; over 300% (+200% or higher) it is "mismatch ↑". Either way the listing is treated as matched to the wrong card: never a hit, and left out of the book, the sold prices, λ and the trends. The rule is skipped when PriceCharting has fewer than 20 sales a year behind its price, when the set is under 30 days old, and on the cheap side for MP/HP copies. The numbers are constants at the top of the collector (PC_LOW, PC_HIGH, PC_MIN_SALES, PC_NEW_SET_D). Sort this column ascending to check the cheapest-looking matches by hand.', e: '$40 against $120 → −66.7% → mismatch ↓. $420 → +250.0% → mismatch ↑. $70 → −41.7% → judged normally.'},
  er_vs: {t: 'vs anchor %', f: '(total ÷ A − 1) × 100', m: 'How far the listing sits below (negative) or above what buyers pay for the card. A hit at a 10% margin needs roughly −31% from the Sell price, which is itself a few percent under A; under −55% the row says "review" instead.', e: 'Total $58, A $94 → −38.3%.'},
  er_profit: {t: 'Profit $ — for this listing', f: 'Net $ of the card − All-in $ of the listing', m: 'What you would clear buying this copy at its price and selling at this listing\'s Sell price (its floor computed without itself). Negative means the listing is above break-even. It is the same number whatever Margin you set; Margin only decides where PASS starts.', e: 'Net $67.80, all-in $61.62 → $6.18.'},
  er_roi: {t: 'ROI % — for this listing', f: 'Profit $ ÷ All-in $ × 100', m: 'Return on the cash tied up in this copy. PASS is exactly ROI ≥ your Margin setting. Sort the tab by this column descending to see the best buys first; judge against the card\'s Exp. days for profit per day.', e: '$6.18 ÷ $61.62 = 10.0% — at a 10% margin, so it just passes.'},
  er_time: {t: 'Time (h)', f: 'hours from listing to sale / end / gone; for an open listing, hours open so far (greyed)', m: 'How long this copy took to move, or how long it has been sitting. Read it against the card\'s Hrs to sale: a copy that sold in 3 hours on a card whose median is 40 says the price was low; an open copy past the median says it is priced above the buyers.', e: 'sold, 6.5 = it sold six and a half hours after listing. open, 30.2 = listed 30 hours ago and still for sale.'},
  lp: {t: 'LP correction (%)', f: 'per price tier: 1 − median over LP sales of (LP sale total ÷ median NM/unstated sale total of the same card within ±7 days)', m: 'How much less a Lightly Played copy sells for than a Near Mint one. It is used twice: inside the eBay Catalog every LP price is lifted to NM-equivalent (an LP sale at $83 counts as $94.32 at 12%), so Price, the floor and the Sell price are NM prices; and on Raw Data a listing that says LP has its sell price cut by it, so its Max buy, Profit, ROI and verdict are for a played copy. Not-stated listings are treated as NM. The number is read-only: it starts at 12% and is replaced by the measured ratio for a tier once that tier has 30 LP sales behind it (green outline); until then a tier uses the ratio measured across all tiers, and until that has 30 sales, the default. Hover a tier for where it stands. Pooled across all cards because one card never has enough LP sales to measure on its own; split by price tier because condition costs more on an expensive card.', e: 'A card sells NM at $95 and its LP copies at $83 → ratio 0.874 → 12.6% discount. If the <$100 tier has 41 such sales with a median of 0.90, that tier shows 10.0%.'},
  er_risk: {t: 'Risk — the scam screen', f: 'points: <50% of the card\'s price +4 · 50–65% +2 · 65–75% +1 (bands 5 points higher on $100+ cards) · seller feedback under 10 +3 · unknown +1 · one photo +1 · 3+ copies of a $75+ card +2 · photo also used by another seller = suspect by itself · delivery window over 10 days +1 · Top Rated Plus −2 · 500+ feedback at 99%+ −1. Score ≥ 5 = suspect, 3–4 = watch.', m: 'A cheap screen for the listings that are most likely not what they claim: a thin account, a deep discount, a borrowed photo, a stack of a card that does not come in stacks. No single signal decides — an honest new seller at a fair price scores 3 (watch) and stays. Suspect listings are kept out of every Catalog statistic (the book, sold prices, λ) so a fake copy cannot drag a card\'s price down, and they are hidden here behind the Show suspects box. Watch listings stay in the statistics but are never allowed to set the floor. A same-day burst of $75+ listings from a seller with no history pushes a watch listing to suspect. Hover the badge for the score and its reasons; the Scam screen button shows how past tiers and signals actually turned out.', e: '45% of the card\'s price (+4), 3 feedback (+3), one photo (+1), quantity 5 (+2) → 10, suspect. 80% of price, 5 feedback (+3) → 3, watch.'},
  er_photos: {t: 'Photos', f: 'number of photos on the listing', m: 'You need the front and the back to judge condition, so listings with fewer than 2 photos are left out of this tab (the count in the header line shows how many). Two photos is a minimum, not a promise — it is often the front plus a close-up, so still look. One photo is also a point on the scam score. The Catalog still counts these listings, because buyers buy from them and they are real competitors.', e: '4 = a front, a back and two close-ups. 1 = left out.'},
  er_verdict: {t: 'Verdict', f: 'PASS if all-in ≤ Max buy for this listing; otherwise the first reason it fails', m: 'Checks in order: "fewer than 2 photos" and "suspect" (hidden by default); "mismatch ↓ / ↑" (priced under 40% or over 300% of the PriceCharting price — treated as a wrong match, see vs PC %); "no sales yet" (no anchor); "too few sales (n)" (under 5 behind the anchor); "not liquid" (the card does not clear your Confidence inside your Window); "condition MP/HP"; the count-aware seller bar ("seller < 98%" for 100+ ratings, "< 95%" for 20–99); "review" (under 45% of A — check photos and seller first); then the price test against this listing\'s own Max buy, computed with the listing left out of the floor. "LEAD" is not a pass: the card has too few eBay sales to judge, and the listing clears the same test when PriceCharting\'s price is used instead, capped by the cheapest other copy (README section 7). A listing that passes on price has its item specifics read by the collector: "PASS ✓" = card number, name and set agree with the matched card; "PASS ID?" = not read yet or left blank by the seller; "ID conflict" = they describe another card (hover for what disagreed).', e: 'All-in $61.62 vs Max buy $61.63 → PASS. All-in $74.38 → "over max buy". Passing on price but listed as Language: Japanese → "ID conflict".'},
  er_cond: {t: 'Cond', f: 'condition words found in the title: NM, LP, MP, HP (n/s = not stated)', m: 'Only NM, LP and not-stated copies count as comparable. An LP listing gets the LP correction applied to its Max buy; not stated is treated as NM. MP/HP copies are shown but fail the gate, and they are excluded from the book and the sales history. The Condition chip in the filters shows or hides each of NM, LP and n/s (MP/HP rows appear only when all three are ticked).', e: '"Near Mint" or "NM" → NM; "lightly played" → LP.'},
  er_bo: {t: 'Offer', f: 'BO = the listing accepts Best Offers', m: 'You can usually get ~10% under the ask; the book ranks these copies at 90% for that reason. When one of these sells, the recorded price is the ask, so it may overstate the true sale.', e: ''},
  er_seller: {t: 'Seller fb / %', f: 'the seller\'s feedback count and positive percentage', m: 'The gate wants ≥ 98% (blank is tolerated). For raw cards, also prefer ≥ 50 feedback — a brand-new seller with a too-cheap card is the classic scam profile.', e: '512 feedback at 99.5%.'},
  er_status: {t: 'Status', f: 'open · sold · ended · gone · stale', m: 'open = still for sale at last check. sold = eBay reports a sale (a listing that disappears in its first 2 days gets a lookup). ended = withdrawn or expired unsold. gone = no longer retrievable. stale = still for sale 2 days after it went up: it did not sell inside your window, and it is not followed further. Sold and ended rows are the raw material for λ and the sold prices.', e: ''},
  trend: {t: 'Trend', f: 'one point per day from the site\'s own snapshots', m: 'Opens the card\'s daily history: sales/yr bars on the left axis, ungraded / retail buy / retail sell on the right, dashed lines for the 90-day high and low and the conservative sell estimate, a hover crosshair, all the statistics, and the buy-gate arithmetic for this card. The history starts the day the site went live and grows by one point each morning.', e: ''}
};
// what each eBay column is built from, and what is built from it (shown in the help popup)
const LINKS = {
  ec_k: ['eBay tracker outcomes', 'λ, Sell-thru, Hot'], ec_d: ['first sighting of the card', 'λ, New/day'],
  ec_n: ['open comparable listings', 'Days supply, the floor'],
  ec_p: ['open comparable listings, Best Offer haircut', 'the floor L (after the credibility rules), Price (when no sales yet)'],
  ec_mu: ['listings first seen in 30 d, Days obs.', 'In/out'], ec_smed: ['last 10 sales', 'Hot (realized check); reference only'],
  ec_s80: ['last 10 sales', 'reference only'], ec_hrs: ['last 10 sales', 'Hot; the future waiting-time λ (see README)'],
  ec_st: ['listings seen 7–37 d ago', 'Hot'],
  ec_lam: ['Sold 30d, Days obs.', 'liquidity (with Confidence and Window), the floor\'s stale rule, Days supply, In/out, P(sale in window), Exp. days'],
  ec_price: ['Anchor A (or p₁)', 'the $50–150 filter, the scam check'], ec_dos: ['Active, λ', 'reading only'], ec_io: ['New/day, λ', 'reading only'],
  ec_A: ['comparable sales, 30 d (60 if thin), trimmed and recency-weighted', 'Sell (the 95% cap), the floor (75% rule), vs anchor %, review band'],
  ec_L: ['open comparable copies, the scam tiers, seller feedback, λ', 'Sell'],
  ec_S: ['Floor L, Anchor A, fast-sale median, calibration', 'Net, Max buy, your list price'],
  ec_prob: ['λ, Window', 'liquid / illiquid'], ec_edays: ['λ, Confidence', 'reading only'],
  ec_maxbuy: ['Sell, Margin, fee, label, supplies', 'Verdict on the Raw Data tab'],
  ec_hot: ['Sold 30d, Sell-thru, Hrs to sale, Sold med vs asks, price trend', 'reading only'],
  et_spm: ['daily rollup of sales', 'Volume drift, the Trend chart'], et_d7: ['7-day median sale price series', 'reading only'], et_d30: ['7-day median sale price series', 'reading only'],
  et_pos: ['7-day median sale price series (90 d)', 'reading only'], et_vd: ['Sales/month now vs the month before', 'reading only'],
  et_vol: ['7-day median sale price series (90 d)', 'reading only'], et_ts: ['7-day median sale price series (30 d)', 'reading only'],
  er_allin: ['Item, Ship, your sales tax', 'Verdict, Profit'], er_verdict: ['All-in, this listing\'s Max buy, liquidity, Cond, Seller %, Anchor, vs PC %, the item-specifics check', '—'], er_vs: ['Total, Anchor A', 'reading only'],
  er_pc: ['PriceCharting daily snapshot (the matched card\'s ungraded price)', 'vs PC %'],
  er_vspc: ['Total, PC ungraded', 'Verdict (mismatch); whether the listing counts in the card\'s book, sold prices and λ'],
  ec_net: ['Sell, fee, label, supplies', 'Max buy, Profit $ on the Raw Data tab'],
  er_profit: ['Net $ of the card (LP-adjusted for LP listings), All-in $ of the listing', 'ROI %'], er_roi: ['Profit $, All-in $', 'reading only (PASS = ROI ≥ Margin)'],
  lp: ['LP sales vs NM/unstated sales of the same card, pooled by price tier', 'Catalog prices (NM-equivalent), Max buy / Profit / ROI / Verdict of LP listings'],
  er_time: ['listing time and outcome time', 'reading only; compare with Hrs to sale'],
  er_risk: ['price vs the card, seller feedback, photos, quantity, photo reuse, returns, delivery window', 'Verdict; suspect listings are excluded from the book, sold prices and λ'],
  er_photos: ['the listing', 'this tab (fewer than 2 = left out), the scam score'],
};
/* ---------------- The pencil: descriptions and READMEs he can rewrite ----------------
   An edit is sent to the collector over the same signed channel as the alert settings (only this page, unlocked with
   the site password, can sign one). The collector keeps it and hands it back in the live file, so it shows on every
   device and survives the daily rebuild. Keys: 'h:<column key>' -> {f, m, e};  'r:<tab>' -> the README's HTML.
   A text longer than one message holds is sent in numbered pieces. Until the collector confirms, the edit is shown
   from PEND; "Restore the original" sends a deletion. */
let OVR = {}, OVR_T = 0;                      // what the collector holds, and the time of its last accepted edit
const PEND = {};                               // key -> {v (null = restore the original), t}
const ovr = key => key in PEND ? PEND[key].v : OVR[key];
const curTab = () => { const p = document.querySelector('.panel:not([hidden])'); return p ? p.id.slice(2) : 'pc'; };
function applyHelp(hp) {                       // called on every live refresh
  OVR = (hp && hp.v) || {}; OVR_T = (hp && hp.t) || 0;
  for (const k of Object.keys(PEND)) if (OVR_T >= PEND[k].t) delete PEND[k];
}
// README text is HTML he typed into the page: keep the plain structure, drop anything that could run or restyle
function cleanHtml(html) {
  const t = document.createElement('template'); t.innerHTML = html;
  const OK = new Set(['H3', 'H4', 'P', 'B', 'I', 'EM', 'STRONG', 'U', 'BR', 'UL', 'OL', 'LI', 'DIV', 'SPAN', 'SUP', 'SUB', 'CODE', 'A', 'TABLE', 'THEAD', 'TBODY', 'TR', 'TH', 'TD']);
  const walk = node => [...node.childNodes].forEach(c => {
    if (c.nodeType === 3) return;
    if (c.nodeType !== 1 || /^(SCRIPT|STYLE|IFRAME|OBJECT|EMBED|LINK|META|FORM|INPUT|BUTTON|TEXTAREA|SELECT|SVG|IMG|VIDEO|AUDIO)$/.test(c.tagName)) return c.remove();
    walk(c);
    if (!OK.has(c.tagName)) return c.replaceWith(...c.childNodes);
    [...c.attributes].forEach(a => { const n = a.name.toLowerCase(); if (!(n === 'class' || (n === 'href' && c.tagName === 'A' && /^https?:\/\//i.test(a.value)))) c.removeAttribute(a.name); });
    if (c.tagName === 'A') { c.setAttribute('target', '_blank'); c.setAttribute('rel', 'noopener'); }
  });
  walk(t.content);
  return t.innerHTML;
}
async function sendEdit(key, value, say) {
  if (typeof HKEY === 'undefined' || !HKEY) return say('This page has no key for the collector, so the edit cannot be saved.', 'warn');
  const b64 = value == null ? '' : btoa(unescape(encodeURIComponent(JSON.stringify(value))));
  const SIZE = 2400, n = Math.max(1, Math.ceil(b64.length / SIZE)), id = Date.now().toString(36) + Math.random().toString(36).slice(2, 6), t0 = Date.now();
  say('Saving…', '');
  try {
    for (let i = 0; i < n; i++) {
      await alSend({type: 'help', t: t0 + i, id, key, i, n, del: value == null ? 1 : 0, d: b64.slice(i * SIZE, (i + 1) * SIZE)});
      if (i < n - 1) await new Promise(r => setTimeout(r, 150));
    }
    PEND[key] = {v: value, t: t0 + n - 1};
    say(value == null ? 'Restored. The collector will confirm in a minute or two.' : 'Saved. The collector will confirm in a minute or two; it then shows on every device.', 'ok');
    return true;
  } catch (e) { say('Could not reach the collector\'s channel (' + e.message + '). Nothing was saved.', 'warn'); return false; }
}
function editBar(bar, hasOvr, onSave, onCancel, onRestore, hint) {
  bar.hidden = false;
  bar.innerHTML = '<button class="go" data-a="save">Save</button><button data-a="cancel">Cancel</button>' + (hasOvr ? '<button data-a="restore">Restore the original</button>' : '') + '<span class="say">' + (hint || '') + '</span>';
  const say = (t, cls) => { const s = bar.querySelector('.say'); s.textContent = t; s.className = 'say ' + (cls || ''); };
  bar.querySelector('[data-a=save]').addEventListener('click', () => onSave(say));
  bar.querySelector('[data-a=cancel]').addEventListener('click', onCancel);
  if (hasOvr) bar.querySelector('[data-a=restore]').addEventListener('click', () => onRestore(say));
  return say;
}

/* ---- the "?" popup ---- */
let HCUR = null;
const helpOf = key => { const h = HELP[key]; if (!h) return null; const o = ovr('h:' + key); return o ? Object.assign({}, h, o) : h; };
function openHelp(key) {
  const h = helpOf(key); if (!h) return;
  HCUR = key;
  $('hbar').hidden = true; $('hedit').hidden = false;
  $('htitle').innerHTML = esc(h.t) + (ovr('h:' + key) ? '<span class="edited">edited by you</span>' : '');
  const L = LINKS[key];
  $('hbody').innerHTML = '<h4>Formula</h4><div class="formula">' + esc(h.f) + '</div><h4>What it means</h4><p>' + esc(h.m) + '</p>' + (h.e ? '<h4>Example</h4><p>' + esc(h.e) + '</p>' : '') +
    (L ? '<h4>Built from</h4><p>' + esc(L[0]) + '</p><h4>Feeds into</h4><p>' + esc(L[1]) + '</p>' : '');
  $('hov').classList.add('open');
}
$('hedit').addEventListener('click', () => {
  const key = HCUR, h = helpOf(key); if (!h) return;
  $('hedit').hidden = true;
  $('hbody').innerHTML = '<h4>Formula</h4><textarea id="he-f" rows="3"></textarea><h4>What it means</h4><textarea id="he-m" rows="10"></textarea><h4>Example</h4><textarea id="he-e" rows="3"></textarea>';
  $('he-f').value = h.f || ''; $('he-m').value = h.m || ''; $('he-e').value = h.e || '';
  editBar($('hbar'), !!ovr('h:' + key),
    async say => { if (await sendEdit('h:' + key, {f: $('he-f').value.trim(), m: $('he-m').value.trim(), e: $('he-e').value.trim()}, say)) setTimeout(() => { if (HCUR === key) openHelp(key); }, 1200); },
    () => openHelp(key),
    async say => { if (await sendEdit('h:' + key, null, say)) setTimeout(() => { if (HCUR === key) openHelp(key); }, 1200); },
    'Plain text. Saved for every device.');
  $('he-m').focus();
});

/* ---- the README, one per tab ---- */
let RCUR = null;
function openReadme(tab) {
  if (!README[tab]) tab = 'pc';
  RCUR = tab;
  const mine = ovr('r:' + tab);
  $('rbar').hidden = true; $('redit').hidden = false;
  $('rtitle').innerHTML = 'README · ' + esc(README_TITLE[tab]) + (mine ? '<span class="edited">edited by you</span>' : '');
  $('rbody').contentEditable = 'false';
  $('rbody').innerHTML = mine ? cleanHtml(mine) : README[tab];
  $('rov').classList.add('open');
}
$('redit').addEventListener('click', () => {
  const tab = RCUR; if (!tab) return;
  $('redit').hidden = true;
  $('rbody').contentEditable = 'true';
  editBar($('rbar'), !!ovr('r:' + tab),
    async say => { const html = cleanHtml($('rbody').innerHTML); if (await sendEdit('r:' + tab, html, say)) setTimeout(() => { if (RCUR === tab) openReadme(tab); }, 1200); },
    () => openReadme(tab),
    async say => { if (await sendEdit('r:' + tab, null, say)) setTimeout(() => { if (RCUR === tab) openReadme(tab); }, 1200); },
    'Type straight into the text below. Saved for every device.');
  $('rbody').focus();
});
$('readme-btn').addEventListener('click', () => openReadme(curTab()));
$('rclose').addEventListener('click', () => $('rov').classList.remove('open'));
$('rov').addEventListener('click', e => { if (e.target === $('rov') && $('rbody').contentEditable !== 'true') $('rov').classList.remove('open'); });
document.querySelectorAll('.help').forEach(b => b.addEventListener('click', e => { e.stopPropagation(); openHelp(b.dataset.h); }));
$('hclose').addEventListener('click', () => $('hov').classList.remove('open'));
$('hov').addEventListener('click', e => { if (e.target === $('hov') && $('hbar').hidden) $('hov').classList.remove('open'); });
